### ISSUE TITLE
Patch cross site scripting (XSS) vulnerability in HTML 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#108]
Fix two cross-site scripting (XSS) vulnerabilities that have been found to be rooted in the file `src/public/templates/search.html`, making the necessary modifications to resolve the issue without disrupting the functionality of the search page on the website.

**Comment by zacharyftw** [comment]
hey @neon-mmd can you assign me this issue

**Comment by neon-mmd** [comment]
> hey @neon-mmd can you assign me this issue

Yes sure 🙂, I will assign this one to you. You may start working on this issue now 🙂 🚀.
