### ISSUE TITLE
Change the font case 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#112]
Change the font case for the word `duckduckgo` from `Duckduckgo` to `DuckDuckGo` in the file `public/templates/engines_tab.html` in the codebase (project folder).

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you 
>     are not familliar with process and add your changes and make a pull request with the changes to this repository and if you 
>     are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started 
>     contributing :slightly_smiling_face: .

**Comment by AlimurtuzaCodes** [comment]
I can fix this issue.

**Comment by neon-mmd** [comment]
Yes sure, go ahead👍I will assign this issue to you 🙂.

**Comment by AlimurtuzaCodes** [comment]
Done PR #117 .
