### ISSUE TITLE
Correct the spelling in the comments 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#113]
Fix the spelling of the word `finishes` in the comments (which all starts with a double slashes in front of the sentences) in the file `public/static/cookies.js` in the codebase (project folder).

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you 
>     are not familliar with process and add your changes and make a pull request with the changes to this repository and if you 
>     are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started 
>     contributing :slightly_smiling_face: .

**Comment by AlimurtuzaCodes** [comment]
Can you assign this issue to me?

**Comment by AlimurtuzaCodes** [comment]
Now I can work on this issue?.

**Comment by alamin655** [comment]
> Now I can work on this issue?.

Yep, go ahead.

**Comment by AlimurtuzaCodes** [comment]
Done PR.
