### ISSUE TITLE
Replace hashes with appropriate links

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#114]
Replace the hashes with appropriate links which will redirect the user to the expected places in the file `public/templates/footer.html` in the codebase (project folder).

``` diff
-<footer>
-    <div>
-       <span>Powered By <b>Websurfx</b></span><span>-</span><span>a lightening fast, privacy respecting, secure meta
-            search engine</span>
-    </div>
-    <div>
-        <ul>
-            <li><a href="#">Source Code</a></li>
-            <li><a href="#">Issues/Bugs</a></li>
-        </ul>
-    </div>
-</footer>
-<script src="static/settings.js"></script>
-</body>
-
-</html>
+<footer>
+    <div>
+       <span>Powered By <b>Websurfx</b></span><span>-</span><span>a lightening fast, privacy respecting, secure meta
+            search engine</span>
+    </div>
+    <div>
+        <ul>
+            <li><a href="https://github.com/neon-mmd/websurfx">Source Code</a></li>
+            <li><a href="https://github.com/neon-mmd/websurfx/issues">Issues/Bugs</a></li>
+        </ul>
+    </div>
+</footer>
+<script src="static/settings.js"></script>
+</body>
+
+</html>
```

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you 
> are not familliar with process and add your changes and make a pull request with the changes to this repository and if you 
> are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started 
> contributing :slightly_smiling_face: .

**Comment by AlimurtuzaCodes** [comment]
Can you assign this issue to me?

**Comment by neon-mmd** [comment]
Yes sure :slight_smile: , I will assign this issue to you. Hope to see you soon with the changes. 

Also I will like to suggest one thing if you don't mind I think let's first complete this and then I will assign the issue #113 to you, what do you say?? :slight_smile:

**Comment by AlimurtuzaCodes** [comment]
Done.

**Comment by AlimurtuzaCodes** [comment]
Done PR #115 .
