### ISSUE TITLE
Rename variables' name to make them kebab cased

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#137]
Rename all variables' name located in all the files located under [`public/static/colorschemes/`](https://github.com/neon-mmd/websurfx/tree/rolling/public/static/colorschemes) folder and also rename all the places where they are being used (referenced) in the file [`public/static/themes/`](https://github.com/neon-mmd/websurfx/blob/rolling/public/static/themes/simple.css). 

The variables that need changing their name are: 
- `--fg` change it to `--foreground-color` 
- `--bg` change it to `--background-color`
- `--1` change it to `--color-one`
- `--2` change it to `--color-two`
- `--3` change it to `--color-three`
- `--4` change it to `--color-four`
- `--5` change it to `--color-five`
- `--6` change it to `--color-six`
- `--7` change it to `--color-seven`

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you 
> are not familliar with process and add your changes and make a pull request with the changes to this repository and if you 
> are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started 
> contributing :slightly_smiling_face: .

**Comment by abhikumar63** [comment]
Hey,
I have gone through the requirements and would like to contribute to the project. I am new to open source world and think this would be a good task in the initial phase of my journey. 
I am familiar with the process and will create a pull request soon. If you want any other changes do let me know.

**Comment by neon-mmd** [comment]
> Hey, I have gone through the requirements and would like to contribute to the project. I am new to open source world and think this would be a good task in the initial phase of my journey. I am familiar with the process and will create a pull request soon. If you want any other changes do let me know.

Yes sure :slightly_smiling_face: , I will assign this issue to you. Hope to see the PR with the changes soon :slightly_smiling_face: .
