### ISSUE TITLE
Patch and improve `Docker` deployment process

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#143]
Improve and fix the docker deployment by editing the `Dockerfile` in the `project folder (codebase)` to make the `workdir` path relative and fix the locations of the files to be copied from and to.

```diff
FROM rust:latest AS chef
# We only pay the installation cost once,
# it will be cached from the second build onwards
RUN cargo install cargo-chef

-WORKDIR app
+WORKDIR /app

FROM chef AS planner
COPY . . 
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

# Build application
COPY . .
RUN cargo install --path .

# We do not need the Rust toolchain to run the binary!
FROM gcr.io/distroless/cc-debian11
-COPY --from=builder ./public/ ./public/
-COPY --from=builder ./websurfx/ ./websurfx/
+COPY --from=builder /app/public/ /opt/websurfx/public/
+COPY --from=builder /app/websurfx/config.lua /etc/xdg/websurfx/config.lua
COPY --from=builder /usr/local/cargo/bin/* /usr/local/bin/
CMD ["websurfx"]
```

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you 
> are not familliar with process and add your changes and make a pull request with the changes to this repository and if you 
> are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started 
> contributing :slightly_smiling_face: .

**Comment by alamin655** [comment]
@neon-mmd Can we add Redis installation and command in here?

**Comment by neon-mmd** [comment]
> @neon-mmd Can we add Redis installation and command in here?

Yes, actually we could, but we already have it in the `docker-compose.yml` so I don't think that having it here again would make any sense :slightly_smiling_face: . Also, I feel having it as a seperate docker container will make it much easier to maintain for the end user, so having it in the `docker-compose.yml` file would be the best idea :slightly_smiling_face: . What do you say??

**Comment by alamin655** [comment]
> > @neon-mmd Can we add Redis installation and command in here?
> 
> Yes, actually we could, but we already have it in the `docker-compose.yml` so I don't think that having it here again would make any sense 🙂 . Also, I feel having it as a seperate docker container will make it much easier to maintain for the end user, so having it in the `docker-compose.yml` file would be the best idea 🙂 . What do you say??

Well, for me, having it in one `Dockerfile` will make it easier for deployment in AWS, GCP, and other cloud services.

**Comment by neon-mmd** [comment]
> > > @neon-mmd Can we add Redis installation and command in here?
> > 
> > 
> > Yes, actually we could, but we already have it in the `docker-compose.yml` so I don't think that having it here again would make any sense slightly_smiling_face . Also, I feel having it as a seperate docker container will make it much easier to maintain for the end user, so having it in the `docker-compose.yml` file would be the best idea slightly_smiling_face . What do you say??
> 
> Well, for me, having it in one `Dockerfile` will make it easier for deployment in AWS, GCP, and other cloud services.

I think you can still deploy it easily on AWS, GCP or any other cloud services. I would suggest, you will just need to `ssh` into the `vps` and then install docker and docker compose and clone the repository and then run this command:

``` shell
cd websurfx
docker compose up -d --build
```

And then you will have `Websurfx` deployed on the `vps`. :slightly_smiling_face:
