### ISSUE TITLE
💬 Should the project be out of testing phase ? 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#150]
Since the project is pretty much stable and also has the features which make it DDoS resistant and evades IP blocking. Also, now with the new feature #146 we have also provided proper error handling. So should the project be removed out of the testing phase ?

**Comment by alamin655** [comment]
> Since the project is pretty much stable and also has the features which make it DDoS resistant and evades IP blocking. Also, now with the new feature #146 we have also provided proper error handling. So should the project be removed out of the testing phase ?

How about next month? 1st Aug?

**Comment by neon-mmd** [comment]
Sorry for being late to reply, I was actually abroad for 9-10 days. Yes, I think this would be a good idea let's make it on next month 1st august 🙂.

**Comment by neon-mmd** [comment]
Since this issue has been resolved, so I am closing this issue :slightly_smiling_face: . By the way, thanks :heart:  for your suggestion, alamin655.
