### ISSUE TITLE
💬 Using `leptos` framework for the next release `v2.0.0` ?

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#155]
After some research, it seems that `leptos` would be better for privacy as it uses `wasm` instead of JavaScript, which has been found to be really bad for privacy. Also, the `leptos` framework provides the feature of `SSR (server side rendering)`  which makes it faster than frameworks like `Solidjs`. So with the help of `leptos` it seems that we will be able to reduce the amount of JavaScript used drastically. So should we move to `leptos` for the next release `v2.0.0` ?

For more information on `leptos`. Check out the link below:
[https://github.com/leptos-rs/leptos](https://github.com/leptos-rs/leptos)

Also, using `leptos` will allow us to provide feature based compiling which will provide more privacy to the user according to what features they choose, which will look something like:
- `Default:` It will use `wasm` and `js` with `csr` and `ssr`.
- `Harderned:` It will use `ssr` only with some `js`
- `Harderned-with-no-scripts:` It will use `ssr` only with no `js` at all.

**Comment by neon-mmd** [comment]
@xffxff @alamin655 what do you say ? Should we rewrite the app in `leptos` in the next release?

**Comment by xffxff** [comment]
> what do you say ? Should we rewrite the app in `leptos` in the next release?

I don't have much experience with front-end development, but I'm open to new tools. So, why not give `leptos` a try?

**Comment by neon-mmd** [comment]
> > what do you say ? Should we rewrite the app in `leptos` in the next release?
> 
> I don't have much experience with front-end development, but I'm open to new tools. So, why not give `leptos` a try?

Ok, cool :rocket:, then let's rewrite the app in `leptos` in the next release :slightly_smiling_face: .

**Comment by lxrst** [comment]
> [Leptos] uses `wasm` instead of JavaScript, which has been found to be really bad for privacy.

WASM is no better than JavaScript for privacy and [can actually be worse in some cases](https://arxiv.org/abs/2307.00143).
Also, while I've achieved small WASM binaries before (~22KB), it takes a significant and very deliberate effort to do so. 5MB WASM load times and memory usage for a search engine isn't good.
I highly recommend using as little JS as possible and no WASM.

**Comment by alamin655** [comment]
> > [Leptos] uses `wasm` instead of JavaScript, which has been found to be really bad for privacy.
> 
> WASM is no better than JavaScript for privacy and [can actually be worse in some cases](https://arxiv.org/abs/2307.00143). Also, while I've achieved small WASM binaries before (~22KB), it takes a significant and very deliberate effort to do so. 5MB WASM load times and memory usage for a search engine isn't good. I highly recommend using as little JS as possible and no WASM.

Yep, I agree with you about keeping as little JS as possible. And neon-mmd has tried to rewrite the app in Leptos, but it didn't go well. Here is a link to it: https://github.com/neon-mmd/websurfx/issues/325#issuecomment-1813253798.

**Comment by neon-mmd** [comment]
> > [Leptos] uses `wasm` instead of JavaScript, which has been found to be really bad for privacy.
> 
> WASM is no better than JavaScript for privacy and [can actually be worse in some cases](https://arxiv.org/abs/2307.00143). Also, while I've achieved small WASM binaries before (~22KB), it takes a significant and very deliberate effort to do so. 5MB WASM load times and memory usage for a search engine isn't good. I highly recommend using as little JS as possible and no WASM.

Ok thanks ❤️ for sharing never knew about this because there seems to be very little information about this topic on the internet currently. Also which does not clearly highlight about the privacy concerns of using it. So thanks again for sharing this. We really appreciate it 👍 🙂 .

Also, about the JS yes we already planning to have it as less as possible like how searx and searxng have very little JS. We are also following the same principles but we also plan to have features based approach to user so that they can choose the privacy level they want according to their threat level. So basically our idea is that for the next release we will provide two features one called the default and another the harderned one. The harderned will not use any JS at all (in other words JS free) while the default will use some amount of JS. That's our idea. Also we are already planning to work on the feature based approach maybe from today itself. 🙂
