### ISSUE TITLE
🔧 Improve the documentation of the config 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#156]
The documentation in the config file (located in `websurfx/config.lua` the project folder (codebase)) seems to be out of sync with the introduction of new colorschemes in the PR #77. It requires to be updated with the mentioning of new colorscheme names in the documentation.

``` diff
 -- ### General ###
logging = true -- an option to enable or disable logs.
debug = false -- an option to enable or disable debug mode.

 -- ### Server ###
port = "8080" -- port on which server should be launched
binding_ip = "127.0.0.1" --ip address on the which server should be launched.
production_use = false -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
 -- if production_use is set to true
 -- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.

 -- ### Website ###
 -- The different colorschemes provided are:
 -- {{
 -- catppuccin-mocha
+-- dark-chocolate
 -- dracula
+-- gruvbox-dark
 -- monokai
 -- nord
 -- oceanic-next
+-- one-dark
 -- solarized-dark
 -- solarized-light
+-- tokyo-night
 -- tomorrow-night
 -- }}
colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
theme = "simple" -- the theme name which should be used for the website

 -- ### Caching ###
redis_url = "redis://127.0.0.1:8082" -- redis connection url address on which the client should connect on.

 -- ### Search Engines ###
upstream_search_engines = { DuckDuckGo = true, Searx = false } -- select the upstream search engines from which the results should be fetched.
```

> **Note**
> 1. The green color lines are lines that are need to be added in the file and in the same position as given above.
> 2. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 3. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you 
> are not familliar with process and add your changes and make a pull request with the changes to this repository and if you 
> are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started 
> contributing :slightly_smiling_face: .

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by neon-mmd** [comment]
> Can I work on this?

We are sorry we will not be able to assign this issue to you because someone has already worked on this issue by submitting, but you can look forward to the upcoming `good-first-issues` which I am going to open soon :slightly_smiling_face: .
