### ISSUE TITLE
✨ Filter user specified content from search results using a `blacklist` and `Allowlist`.

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#163]
Provide a way to filter out all user specified content to be filtered out using a blacklist and allowlist by checking the result header, URL, and result description using regex.

For example:

if the result shows:

``` markdown
# Some nsfw header
nsfw-url
nsfw desc
```

Then filter out this result by matching the NSFW word or URL by checking first the header then URL and finally the description if any of the three contains the NSFW word when matching it against the `blacklist`. Then filter out the result out by removing it from the `result_map` and adding in a temporary `blacklist_map`. Also, after the results are filtered, check whether the filtered out results do not contain false positives by checking each result in the `blacklist_map`. This is similar to how it was done previously by using regex but this time against the `allowlist`. If a false positive result is found, then remove it from the `blacklist_map` and insert it back into the `result_map`.

**Comment by neon-mmd** [comment]
@xffxff are you interested in working on this issue? If you are, then I will assign this issue to you :slightly_smiling_face: .

**Comment by xffxff** [comment]
> @xffxff are you interested in working on this issue? If you are, then I will assign this issue to you 🙂 .

Yes, I'm interested in working on this issue. But I haven't had experience with something like this before, if I encounter difficulties, I may need your help @neon-mmd

**Comment by neon-mmd** [comment]
> > @xffxff are you interested in working on this issue? If you are, then I will assign this issue to you slightly_smiling_face .
> 
> Yes, I'm interested in working on this issue. But I haven't had experience with something like this before, if I encounter difficulties, I may need your help @neon-mmd

Yes sure, no problem if you need help I will help you out :slightly_smiling_face: .

**Comment by xffxff** [comment]
I'm sorry, I don't have enough free time recently to do this @neon-mmd

**Comment by neon-mmd** [comment]
> I'm sorry, I don't have enough free time recently to do this @neon-mmd

It is ok no problem, I can understand it, but thanks :heart:  for informing it beforehand. This helps a ton. :slightly_smiling_face:
