### ISSUE TITLE
🐛 Unable to search and get error (111)

### ISSUE THREAD

**Issue by The-Ducktor** [neon-mmd/websurfx#168]
**Version of Websurfx, commit number if you are using on master branch**

**How did you install Websurfx?**
Docker
**What happened?**

when i try to search anything i get a error (Connection refused (os error 111)

**Steps To Reproduce**

install with docker normally
**Expected behavior**
get a search result i suppose

**Comment by alamin655** [comment]
Just tried it and it's working for me.

Can you provide the `config.lua` file.

**Comment by The-Ducktor** [comment]
[config.lua.zip](https://github.com/neon-mmd/websurfx/files/12234729/config.lua.zip)
I think i just copied whatever the example one way mostly

**Comment by alamin655** [comment]
> [config.lua.zip](https://github.com/neon-mmd/websurfx/files/12234729/config.lua.zip) I think i just copied whatever the example one way mostly

Are you using the `stable` release of the project or the `rolling` release?

If you are using `stable`, I would say use `rolling` instead, as it's more updated.

And then check your `config.lua` file and change it to:

```lua
-- ### General ###
logging = true -- an option to enable or disable logs.
debug = false -- an option to enable or disable debug mode.

-- ### Server ###
port = "8080" -- port on which server should be launched
binding_ip_addr = "0.0.0.0" --ip address on the which server should be launched.
production_use = false -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users)
-- if production_use is set to true
-- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
request_timeout = 60 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).

-- ### Website ###
-- The different colorschemes provided are:
-- {{
-- catppuccin-mocha
-- dark-chocolate
-- dracula
-- gruvbox-dark
-- monokai
-- nord
-- oceanic-next
-- one-dark
-- solarized-dark
-- solarized-light
-- tokyo-night
-- tomorrow-night
-- }}
colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
theme = "simple" -- the theme name which should be used for the website

-- ### Caching ###
redis_connection_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.

-- ### Search Engines ###
upstream_search_engines = { DuckDuckGo = true, Searx = false } -- select the upstream search engines from which the results should be fetched.
```
You can change the `binding_ip_addr` to your preferred IP address.

If the `binding_ip_addr` is set to `0.0.0.0`, it means that the server will bind to all available network interfaces on the host, which includes the loopback interface `(127.0.0.1)` as well as any other network interfaces available on the host machine.

In this case, if you run the server without changing anything, it will be accessible at the IP address of your machine, as well as at the loopback address `127.0.0.1`. The URL you would use to access the server would depend on the specific IP address assigned to your machine on the network.

For example, if your machine's IP address is `192.168.1.100`, and you are running the server on port `8080` as specified in the configuration file, you would access the server using the URL `http://192.168.1.100:8080/` or `http://127.0.0.1:8080/` in your web browser.

**Comment by The-Ducktor** [comment]
was using the `rolling` release and attempted to follow the provided instructions, but unfortunately, I have encountered further setbacks. The application docker container now consistently quits immediately whenever I attempt to launch it. I apologize for any inconvenience caused and for my lack of help in handling this matter.  and what got me my orginal result was setting the `binding_ip_addr` to `0.0.0.0` as if else it does nothing even if i got to `127.0.0.1:8080` nothing is shown while when i set it to `0.0.0.0` i get to the search page but then get the original error

I get this from the logs in that container

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
/websurfx.rs:19:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
/websurfx.rs:19:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
/websurfx.rs:19:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
/websurfx.rs:19:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by alamin655** [comment]
Hey @neon-mmd can you check on this?

**Comment by neon-mmd** [comment]
> Hey @neon-mmd can you check on this?

Yes sure no problem :slightly_smiling_face:  I will check on this.

**Comment by neon-mmd** [comment]
> was using the `rolling` release and attempted to follow the provided instructions, but unfortunately, I have encountered further setbacks. The application docker container now consistently quits immediately whenever I attempt to launch it. I apologize for any inconvenience caused and for my lack of help in handling this matter. and what got me my orginal result was setting the `binding_ip_addr` to `0.0.0.0` as if else it does nothing even if i got to `127.0.0.1:8080` nothing is shown while when i set it to `0.0.0.0` i get to the search page but then get the original error
> 
> I get this from the logs in that container
> 
> ```rust
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
> Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
> /websurfx.rs:19:34
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
> Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
> /websurfx.rs:19:34
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
> Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
> /websurfx.rs:19:34
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromLuaConversion
> Error { from: "nil", to: "String", message: Some("expected string or number") }', src/bin
> /websurfx.rs:19:34
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Sorry, but we will ask a few questions in order to better understand and diagnose the problem. If you don't mind, can you please provide us with the steps you used to deploy it with docker? . Also, what command are you using to run the docker container ? :slightly_smiling_face:

**Comment by The-Ducktor** [comment]
Sure I was using the commands in the [Instructions](https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md) the `docker compose up -d --build` and copied with the other command provided `git clone https://github.com/neon-mmd/websurfx.git
cd websurfx` besides that i just used i just changed the `binding_ip_addr` as I stated earlier I have no idea what I'm doing wrong

**Comment by neon-mmd** [comment]
> Sure I was using the commands in the [Instructions](https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md) the `docker compose up -d --build` and copied with the other command provided `git clone https://github.com/neon-mmd/websurfx.git cd websurfx` besides that i just used i just changed the `binding_ip_addr` as I stated earlier I have no idea what I'm doing wrong

I think I found the problem and I would suggest replacing your `config.lua` to the one specified in the `docs` [here](https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#unstableedgerolling) under the section `unstable/edge/rolling`. This will solve the problem :slightly_smiling_face: .

As an example, here is my config:

```lua
-- ### General ###
logging = true -- an option to enable or disable logs.
debug = false -- an option to enable or disable debug mode.
threads = 10 -- the amount of threads that the app will use to run (the value should be greater than 0).

-- ### Server ###
port = "8080" -- port on which server should be launched
binding_ip = "0.0.0.0" --ip address on the which server should be launched.
production_use = false -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
-- if production_use is set to true
-- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
request_timeout = 30 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).

-- ### Website ###
-- The different colorschemes provided are:
-- {{
-- catppuccin-mocha
-- dark-chocolate
-- dracula
-- gruvbox-dark
-- monokai
-- nord
-- oceanic-next
-- one-dark
-- solarized-dark
-- solarized-light
-- tokyo-night
-- tomorrow-night
-- }}
colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
theme = "simple" -- the theme name which should be used for the website

-- ### Caching ###
redis_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.

-- ### Search Engines ###
upstream_search_engines = { DuckDuckGo = true, Searx = true } -- select the upstream search engines from which the results should be fetched.
```

**Comment by The-Ducktor** [comment]
Now I get to the home page again, but when I click search I get `key must be a string at line 1 column 2` when connect from `127.0.0.1:8080 / Localhost:8080`

And now works when on I connect from `0.0.0.0:8080` so kinda solved I suppose?

And for a second it worked from `localhost:8080` and was fast while for `0.0.0.0:8080`  it was kinda slow, so this seems very odd

and after clear cache for localhost and 127.0.1 it works now we can probably close the issue now

**Comment by neon-mmd** [comment]
> Now I get to the home page again, but when I click search I get `key must be a string at line 1 column 2` when connect from `127.0.0.1:8080 / Localhost:8080`
> 
> And now works when on I connect from `0.0.0.0:8080` so kinda solved I suppose?
> 
> And for a second it worked from `localhost:8080` and was fast while for `0.0.0.0:8080` it was kinda slow, so this seems very odd
> 
> and after clear cache for localhost and 127.0.1 it works now we can probably close the issue now

Ok I see, Actually when you connect something with `0.0.0.0` the operating system tends to check whether the app is running on the `127.0.0.1` or `your ip address` and then it will choose the one it is running on and connect to it. So because of this when you connect on `0.0.0.0` it will look as it is an operating system issue. So because of this, I would generally recommend and suggest you to connect on the `127.0.0.1` IP. This tends to avoid the operating system because it makes it explicit as to which IP address to connect on, which will make it fast. 

Also, just a suggestion if you found any difficulty in understanding the docs then feel free to open a PR to improve it as this will help others in future to better understand the `docs`.
