### ISSUE TITLE
🔧 Add more detailed logging for debugging

### ISSUE THREAD

**Issue by xffxff** [neon-mmd/websurfx#170]
I'm creating this issue to request an enhancement to the current logging system of websurfx. While searching on the web, I encountered a situation where I received an empty result in the web interface. However, the current server logs did not provide any information to understand the reason behind this.

![image](https://github.com/neon-mmd/websurfx/assets/30254428/9f80d524-3c81-42d2-8830-3c55d05454c2)
![image](https://github.com/neon-mmd/websurfx/assets/30254428/1420bb22-25f0-4d93-9fbf-d9d210c8ee79)

It was unclear whether the empty result was due to a request timeout, an issue with the upstream engine, or some other unknown factor. More detailed logs would greatly help in troubleshooting these kinds of issues in the future.

**Comment by alamin655** [comment]
I also experienced something similar.

![image](https://github.com/neon-mmd/websurfx/assets/129589283/0ac1ff16-3b26-405d-806c-a05e010e6f67)

**Comment by xffxff** [comment]
> I also experienced something similar.

@alamin655 After adding a line to log the engine error, it was due to the request timeout to the upstream engine
![image](https://github.com/neon-mmd/websurfx/assets/30254428/af4e1443-380e-4ee3-ac16-85c7338de852)


![image](https://github.com/neon-mmd/websurfx/assets/30254428/cfd8ecee-ecfe-4486-995c-6f126b10c49d)

**Comment by alamin655** [comment]
> > I also experienced something similar.
> 
> @alamin655 After adding a line to log the engine error, it was due to the request timeout to the upstream engine ![image](https://user-images.githubusercontent.com/30254428/257714283-af4e1443-380e-4ee3-ac16-85c7338de852.png)
> 
> ![image](https://user-images.githubusercontent.com/30254428/257713524-cfd8ecee-ecfe-4486-995c-6f126b10c49d.png)

Ohk, so a new PR to add a more detailed log will be better, I guess.

**Comment by neon-mmd** [comment]
> I'm creating this issue to request an enhancement to the current logging system of websurfx. While searching on the web, I encountered a situation where I received an empty result in the web interface. However, the current server logs did not provide any information to understand the reason behind this.
> 
> ![image](https://user-images.githubusercontent.com/30254428/257671824-9f80d524-3c81-42d2-8830-3c55d05454c2.png) ![image](https://user-images.githubusercontent.com/30254428/257671882-1420bb22-25f0-4d93-9fbf-d9d210c8ee79.png)
> 
> It was unclear whether the empty result was due to a request timeout, an issue with the upstream engine, or some other unknown factor. More detailed logs would greatly help in troubleshooting these kinds of issues in the future.

I think the problem has to do with the DuckDuckGo search engine, it tends to not provide as many such results. So I think we will need to add a documentation in the config like DuckDuckGo should not be used standalone as it does not provide as many results and should always be used in combination with other search engines.

Also, For the logging I would suggest not having it because there is an upcoming feature which will provide a menu box with a list of errors that occurred while querying that engine in the UI. The menu box will look something like this.

```
EngineName    (ErrorType)   SeverityIndicationWithColor
```

Already with previous PR #145 there is already a mechanism that has been implemented to propagate the error to the UI with the aggregated search results (which is in JSON). So if you log the results in the routes.rs under the `search` function, you will find that the errors do get propagated. So we are just missing the implementation of the error box in the UI, which will be done soon in the next PR :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
> > I'm creating this issue to request an enhancement to the current logging system of websurfx. While searching on the web, I encountered a situation where I received an empty result in the web interface. However, the current server logs did not provide any information to understand the reason behind this.
> > ![image](https://user-images.githubusercontent.com/30254428/257671824-9f80d524-3c81-42d2-8830-3c55d05454c2.png) ![image](https://user-images.githubusercontent.com/30254428/257671882-1420bb22-25f0-4d93-9fbf-d9d210c8ee79.png)
> > It was unclear whether the empty result was due to a request timeout, an issue with the upstream engine, or some other unknown factor. More detailed logs would greatly help in troubleshooting these kinds of issues in the future.
> 
> I think the problem has to do with the DuckDuckGo search engine, it tends to not provide as many such results. So I think we will need to add a documentation in the config like DuckDuckGo should not be used standalone as it does not provide as many results and should always be used in combination with other search engines.
> 
> Also, For the logging I would suggest not having it because there is an upcoming feature which will provide a menu box with a list of errors that occurred while querying that engine in the UI. The menu box will look something like this.
> 
> ```
> EngineName    (ErrorType)   SeverityIndicationWithColor
> ```
> 
> Already with previous PR #145 there is already a mechanism that has been implemented to propagate the error to the UI with the aggregated search results (which is in JSON). So if you log the results in the routes.rs under the `search` function, you will find that the errors do get propagated. So we are just missing the implementation of the error box in the UI, which will be done soon in the next PR slightly_smiling_face .

Based on my previous comment. So should we really need to have logs for request timeouts ? :slightly_smiling_face:

**Comment by xffxff** [comment]
> Also, For the logging I would suggest not having it because there is an upcoming feature which will provide a menu box with a list of errors that occurred while querying that engine in the UI.

It is great to have a menu box in the UI that displays a list of errors that occurred while querying that engine. However, I believe we should also include more logs, especially when an error occurs. This would be helpful for developers to locate the bug. For instance, by logging the error on the server side, we can easily obtain the backtrace of the error. On the other hand, if we only display the error in the UI, we can understand what the error is, but not where it occurred

**Comment by neon-mmd** [comment]
> > Also, For the logging I would suggest not having it because there is an upcoming feature which will provide a menu box with a list of errors that occurred while querying that engine in the UI.
> 
> It is great to have a menu box in the UI that displays a list of errors that occurred while querying that engine. However, I believe we should also include more logs, especially when an error occurs. This would be helpful for developers to locate the bug. For instance, by logging the error on the server side, we can easily obtain the backtrace of the error. On the other hand, if we only display the error in the UI, we can understand what the error is, but not where it occurred

Ok, Thanks :heart:  for taking the time to explaining this now I really got the point on why should we have the logs for the `engine errors` as well. I think I will add this in the currently being worked PR #176 as it might be the right place to add this in. :slightly_smiling_face:
