### ISSUE TITLE
✨ Publish the app as a package on AUR

### ISSUE THREAD

**Issue by v1rtl** [neon-mmd/websurfx#212]
**Is your feature request related to a problem? Please describe.**

It takes some time to build a server, initialize a database and then create a systemd service. Would be nice to have an AUR package that does all that already.

**Describe the solution you'd like**

a package on AUR

**Describe alternatives you've considered**

Set up from scratch

**Comment by neon-mmd** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> It takes some time to build a server, initialize a database and then create a systemd service. Would be nice to have an AUR package that does all that already.
> 
> **Describe the solution you'd like**
> 
> a package on AUR
> 
> **Describe alternatives you've considered**
> 
> Set up from scratch

Thanks :heart: for taking the time to open this issue. We really appreciate it :+1: It really helps improve the project. Actually, we already have this packaged in this AUR. You can check it out [here](https://aur.archlinux.org/packages/websurfx-edge-git) . Also, you can install it by following steps:

```bash
yay -S websurfx-edge-git
```

OR

```bash
paru -S websurfx-edge-git
```

**Comment by Riverside96** [comment]
Would adding a Nix flake be beneficial?
There was a hard requirement for Rust to be installed via rustup & compilation was very slow using yay.
This could be improved by nix's caching.

**Comment by neon-mmd** [comment]
> Would adding a Nix flake be beneficial? There was a hard requirement for Rust to be installed via rustup & compilation was very slow using yay. This could be improved by nix's caching.

Yes, I think it would be a great idea. I would suggest having it packaged as nix flake. I am already looking forward to having the app packaged for Snap, AppImage and Flatpak as well. 

Also, if caching doesn't help, then I think I can automate the process of creating a binary file with the releases. What do you say?

**Comment by v1rtl** [comment]
sorry I didn't notice the AUR package, I think this can be closed

but it's worth adding to readme that for arch Linux you can use this

**Comment by neon-mmd** [comment]
> sorry I didn't notice the AUR package, I think this can be closed
> 
> but it's worth adding to readme that for arch Linux you can use this

Ok, no problem  :slightly_smiling_face: , but I would also suggest taking a look at [this](https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#arch-linux) as well, here we provide the documentation for how to install and get things setup.

**Comment by neon-mmd** [comment]
Thanks :heart: once again for opening this issue. Because it really helps us improve our project.  As such, we really appreciate it :+1: .  I think I will close this issue now because I think the feature request has been already met before. But, if you find any difficulties or bugs or doubts, feel free to ask them, opening a new issue :slightly_smiling_face: .
