### ISSUE TITLE
🐛 build error unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by martinellison** [neon-mmd/websurfx#214]
**Version of Websurfx, commit number if you are using on master branch**

current on stable branch

**How did you install Websurfx?**
followed README

**What happened?**
build error

**Steps To Reproduce**
run build as per README

**Expected behavior**
build succeeded

**Error message from build:**

```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to report this bug. We really appreciate it :+1: as this helps us improve the project. I think I would suggest taking a look at this issue #134 because I think this issue is related to that one.

**Comment by martinellison** [comment]
I set the default to stable and then it built without error, so I am closing this issue thanks. _Edit: I am now able to run websurfx and make searches, thanks._
