### ISSUE TITLE
✨ Inform user with appropriate error message when none of the engines are selected

### ISSUE THREAD

**Issue by arctic-byte** [neon-mmd/websurfx#227]
**Request & Problem**
I forgot to select and engine and the search still loaded telling me that it couldn't find a result for that search.

**My recommended solution**
I think it would be better to inform the user that no engine was selected and provide him with a button that redirects him to the corresponding settings.

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to open this issue. We really appreciate it :+1: As this really helps improve our project. I think this is a very good idea!!  I think I will be working on it soon :slightly_smiling_face: . So thanks :heart:  again for suggesting this cool feature :slightly_smiling_face: .
