### ISSUE TITLE
Handle "reqwest" Errors 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#23]
Use an enum to handle `reqwest` errors by adding an enum something like this:

``` rust
enum ReqwestError{
  NotFound,
  Timeout,
  Forbidden,
  AccessDenied,
  TooManyRequests
}
``` 

Getting the Html content from the upstream and grabbing the data and if an error occurs or if an error is found on the page then returning an appropriate enum variant.

**Comment by XFFXFF** [comment]
@neon-mmd  I think we can define a specific error type that wraps `reqwest::Error`. Here's an example implementation:

```rust
enum Error {
    ReqwestError(reqwest::Error),
    // add other error types as needed
}
```
We can then use this `Error` type instead of `Box<dyn std::error::Error>` in the signature of the [`results`](https://github.com/neon-mmd/websurfx/blob/0b196ed3f2b40d19d401abe293a9fda972169292/src/engines/duckduckgo.rs#L28-L32) function. By checking for [`is_redirect`](https://docs.rs/reqwest/latest/reqwest/struct.Error.html#method.is_redirect), [`is_timeout`](https://docs.rs/reqwest/latest/reqwest/struct.Error.html#method.is_timeout), and so on, we can determine the specific error that occurred

**Comment by neon-mmd** [comment]
@XFFXFF Sorry for the late reply, The idea is really great I like it but there is a minor issue with it. The problem is that I am going be adding a button for a popup menu in the UI which will display engine stats for the currently loaded pages showing what went wrong for example it will display something like this:

``` example
Duckduckgo  (access denied)  [a red square showing the priority of the issue (in this case high priority)]
Searx            (Timeout)             [a blue square (low priority)]
```

Also in the future, I would integrate this menu to allow the user to directly open bug issues from there with appropriate issue labels assigned automatically, so this will allow us to handle issues more effectively and efficiently, I hope you got my point :slightly_smiling_face: . So I don't know how we can handle this but I am open to ideas and suggestions :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
@XFFXFF Do you have any idea on how to solve this issue?? I have been really struggling with this so far. Here's what I have been working on:

In the `engine_models.rs` file which I have created under `src/engines` folder, I have written a code something like this:
```  rust
use scraper::error::SelectorErrorKind;

#[derive(Debug)]
pub enum EngineErrorKind<'a> {
    RequestError(reqwest::Error),
    NotFound,
    ExtractionError(SelectorErrorKind<'a>),
}

impl<'a> From<SelectorErrorKind<'a>> for EngineErrorKind<'a> {
    fn from(err: SelectorErrorKind<'a>) -> Self {
        match err {
            _ => Self::ExtractionError(err),
        }
    }
}

impl<'a> From<reqwest::Error> for EngineErrorKind<'a> {
    fn from(err: reqwest::Error) -> Self {
        match err {
            _ => Self::RequestError(err),
        }
    }
}
```

and In the `src/engines/duckduckgo.rs` file. I am changing the returned Result type from `Result<HashMap<String, RawSearchResult>, Box<dyn std::error::Error>>` to `Result<HashMap<String, RawSearchResult>, EngineErrorKind>`. Everything works fine except for this part in the code:
``` rust
    // ----
    // initializing HeaderMap and adding appropriate headers.
    let mut header_map = HeaderMap::new();
    header_map.insert(USER_AGENT, user_agent.parse()?);
    header_map.insert(REFERER, "https://google.com/".parse()?);
    header_map.insert(CONTENT_TYPE, "application/x-www-form-urlencoded".parse()?);
    header_map.insert(COOKIE, "kl=wt-wt".parse()?);
   // ----
```

Any ideas or suggestions on how to fix this issue?? :slightly_smiling_face:

**Comment by xffxff** [comment]
> Everything works fine except for this part in the code:
> 
> ```rust
>     // ----
>     // initializing HeaderMap and adding appropriate headers.
>     let mut header_map = HeaderMap::new();
>     header_map.insert(USER_AGENT, user_agent.parse()?);
>     header_map.insert(REFERER, "https://google.com/".parse()?);
>     header_map.insert(CONTENT_TYPE, "application/x-www-form-urlencoded".parse()?);
>     header_map.insert(COOKIE, "kl=wt-wt".parse()?);
>    // ----
> ```
> 
> Any ideas or suggestions on how to fix this issue?? 🙂

The `user_agent.parse()?`  raises  an `reqwest::header::InvalidHeaderValue`  error, so we need to implement the `From` trait to convert `InvalidHeaderValue` to `EngineErrorKind`. Here is an example implementation:

```rust
impl<'a> From<InvalidHeaderValue> for EngineErrorKind<'a> {
    fn from(err: InvalidHeaderValue) -> Self {
        match err {
            _ => Self::InvalidHeaderValue(err),
        }
    }
}
```

With this implementation, the code should compile.

However, it's worth considering whether or not we need to raise a specific error for this case. It's unlikely that upstream code will specifically handle `InvalidHeaderValue` or `SelectorErrorKind`. Instead, we could simplify our error handling by wrapping them as `UnexpectedError`, similar to `InternalServerError` in HTTP. Here is an updated implementation

```rust
#[derive(Debug)]
pub enum EngineErrorKind {
    RequestError(reqwest::Error),
    UnexpectedError(String),
}

impl<'a> From<SelectorErrorKind<'a>> for EngineErrorKind<'a> {
    fn from(err: SelectorErrorKind<'a>) -> Self {
        match err {
            _ => Self::UnexpectedError(err.to_string()),
        }
    }
}

impl<'a> From<InvalidHeaderValue> for EngineErrorKind<'a> {
    fn from(err: InvalidHeaderValue) -> Self {
        match err {
            _ => Self::UnexpectedError(err.to_string),
        }
    }
}
```

@neon-mmd  What do you say?

**Comment by neon-mmd** [comment]
> The `user_agent.parse()?`  raises a `reqwest::header::InvalidHeaderValue`  error, so we need to implement the `From` trait to convert `InvalidHeaderValue` to `EngineErrorKind`. Here is an example implementation:
> 
> ``` rust
> impl<'a> From<InvalidHeaderValue> for EngineErrorKind<'a> {
>     fn from(err: InvalidHeaderValue) -> Self {
>         match err {
>             _ => Self::InvalidHeaderValue(err),
>         }
>     }
> }
> ```
> 
> With this implementation, the code should compile.
> 

Ok now I see, the `reqwest::header::InvalidHeaderValue` was the problem. I did get compile time errors for this but didn't think this was what the compiler was yelling for :smile: but this was something new to learn. I will take note of this right away. Thanks!! for taking the time for explaining this.

![image](https://github.com/neon-mmd/websurfx/assets/132049916/e0324cac-8a0f-46d7-b732-6283dcdf77f9)

> However, it's worth considering whether or not we need to raise a specific error for this case. It's unlikely that upstream code will specifically handle `InvalidHeaderValue` or `SelectorErrorKind`. Instead, we could simplify our error handling by wrapping them as `UnexpectedError`, similar to `InternalServerError` in HTTP. Here is an updated implementation
> 
> ``` rust
> #[derive(Debug)]
> pub enum EngineErrorKind {
>     RequestError(reqwest::Error),
>     UnexpectedError(String),
> }
> 
> impl<'a> From<SelectorErrorKind<'a>> for EngineErrorKind<'a> {
>     fn from(err: SelectorErrorKind<'a>) -> Self {
>         match err {
>             _ => Self::UnexpectedError(err.to_string()),
>         }
>     }
> }
> 
> impl<'a> From<InvalidHeaderValue> for EngineErrorKind<'a> {
>     fn from(err: InvalidHeaderValue) -> Self {
>         match err {
>             _ => Self::UnexpectedError(err.to_string),
>         }
>     }
> }
> ```
> 
> @neon-mmd  What do you say?
> 

I think this is better :+1: because instead of handling these two errors by giving them two separate error names will be useless as it will not make any sense in this context and I think as you suggested having them both grouped into one error kind will be better :slightly_smiling_face: . So, I agree with your suggestion :slightly_smiling_face: .
