### ISSUE TITLE
🛠️ Make `style` checking and `testing` GitHub action work on conditional compiling app

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#246]
### Description

Provide a fix for the style checking and testing GitHub action so that it works on a conditional compiled (feature based compiled) app. The YAML code for the GitHub action can found in `.github/workflows/rust_format.yml` file located under the codebase (`websurfx` directory) and the changes to be made is shown below in the provided YAML code below from the `rust_format.yml` file. 

``` diff
---
name: Rust format and clippy checks
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "rolling" 

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Install LuaJIT and Lua 
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends liblua5.4-dev liblua5.3-dev liblua5.2-dev liblua5.1-0-dev libluajit-5.1-dev
      - uses: actions/checkout@v2
      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
-         args: --all-features --all-targets --all
+        args: --all-targets --all
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
```

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you are not familliar with process and add your changes and make a pull request with the changes to this repository and if you are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started contributing :slightly_smiling_face: .

### Do you want to work on this issue?

None

**Comment by Sweetdevil144** [comment]
Hello @neon-mmd . Is the issue fixed? If not, then maybe I can work on it and enhance the scalability. This will be altogether a new experience for me and a great oppurtunity to learn something new!!

**Comment by alamin655** [comment]
@Sweetdevil144 Thanks :heart: for your interest in working on this issue. I would be glad to assign this issue to you :slightly_smiling_face: .

---
We have a [Discord server](https://discord.gg/SWnda7Mw5u); feel free to join and share your ideas and ask questions about the project. We would be glad to hear from you.
