### ISSUE TITLE
✨ Provide an official Docker image

### ISSUE THREAD

**Issue by dr460nf1r3** [neon-mmd/websurfx#271]
### Description

While Websurfx already has a Docker/Compose deployment option, there is no official image yet. To easy the deployment process, it would be great to have an official image available which can simply be pulled from a trusted registry.

### Do you want to work on this issue?

No

**Comment by neon-mmd** [comment]
Thanks ❤️ for taking the time to open this issue. We really appreciate it 👍🏻 as this helps improve our project 🙂 . Actually, we already have plans on working on this and we would be working on this soon. 🙂

**Comment by neon-mmd** [comment]
Dr460nf1r3, We have now provided the `official docker image` which is available [here](https://hub.docker.com/r/neonmmd/websurfx). So I would suggest checking it out :slightly_smiling_face: . If you find any issues, let us know here by filing an issue [here](https://github.com/neon-mmd/websurfx/issues). We would be glad to help :slightly_smiling_face: . Also, we will be updating the `docs` providing this information as soon as possible.  

Thanks :heart: again for opening the feature request :slightly_smiling_face: .

**Comment by dr460nf1r3** [comment]
Very nice! ~Will be testing it soon :)~ Having it up [here](https://websurfx.garudalinux.org) :D 

One thing about the `docker-compose.yml`:
>     image: redis:latest
>     ports:
>       - 6379:6379

I think there is no need to expose the ports if using the same compose file since you are inside the same Docker network.


Things I've noticed: 
- settings don't stick for some reason
- my config isn't applied 

The config used can be found [here](https://github.com/garuda-linux/infrastructure-nix/blob/main/docker-compose/all-in-one/docker-compose.yml#L197).

**Comment by neon-mmd** [comment]
> Very nice! ~Will be testing it soon :)~ Having it up [here](https://websurfx.garudalinux.org) :D
> 
> One thing about the `docker-compose.yml`:
> 
> > ```
> > image: redis:latest
> > ports:
> >   - 6379:6379
> > ```
> 
> I think there is no need to expose the ports if using the same compose file since you are inside the same Docker network.

Thanks :heart: for pointing the unnecessary port exposure part out. We would be working on it soon. :slightly_smiling_face: . 

> Things I've noticed:
> 
> * settings don't stick for some reason
> * my config isn't applied
> 
> The config used can be found [here](https://github.com/garuda-linux/infrastructure-nix/blob/main/docker-compose/all-in-one/docker-compose.yml#L197).

I think for this I would suggest opening two new issues for the two bugs you have noticed with a screenshot so that we can have a better idea of the error. Also, by doing this, it allows us to fix and diagnose the problem, Hence I would strongly recommend doing it :slightly_smiling_face: .

**Comment by dr460nf1r3** [comment]
Sure, done now :) This issue can be closed then, as the image is up! Thanks 😊
