### ISSUE TITLE
🛠️ Remove unnecessary unused volume `public`

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#280]
### What would you like to share?

Remove the unnecessary unused mountable volume `public` from the `docker-compose.yml` file which is located in the codebase (`websurfx` directory).

The change that needs to be made in the file is shown below: 

``` diff
---
version: "3.9"
services:
  app:
    image: websurfx:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./websurfx/:/etc/xdg/websurfx/
-      - ./public/:/opt/websurfx/public/
  redis:
    image: redis:latest
    ports:
      - 6379:6379
```
> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you are not familliar with process and add your changes and make a pull request with the changes to this repository and if you are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started contributing :slightly_smiling_face: .  

### Do you want to work on this issue?

None

**Comment by evanyang1** [comment]
count me in

**Comment by neon-mmd** [comment]
> count me in

Yes sure, I will assign this issue to you :slightly_smiling_face:, you may start working on it right away :rocket: .
