### ISSUE TITLE
⚙️ Rewrite the search engine frontend with `maud` html framework

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#302]
### What would you like to share?

Rewrite the search engine frontend with the `maud` html framework to improve the website speed and security.

### Do you want to work on this issue?

None

**Comment by btwshivam** [comment]
please assign me I want to work on it

**Comment by alamin655** [comment]
Thank you for your willingness to contribute. 😊 I will assign you to the issue. If you have any questions or need further information, please don't hesitate to ask. ❤️

---
We have a [Discord server](https://discord.gg/SWnda7Mw5u); feel free to join and share your ideas and ask questions about the project. We would be glad to hear from you.

**Comment by neon-mmd** [comment]
shivam200446, thanks :heart: for working on this. We really appreciate it :+1: I would like to inform that we have updated this Issue to better reflect what changes are required from the issue. So I would suggest going through it :slightly_smiling_face: .
