### ISSUE TITLE
🐛 Settings set via web interface don't stick

### ISSUE THREAD

**Issue by dr460nf1r3** [neon-mmd/websurfx#306]
### Description

If settings get changed at a Docker Compose deployed instance (didn't try other deployment methods), they don't stick. You can try it yourself as follows:

1. visit https://websurfx.garudalinux.org/settings
2. change any setting, eg. the search engines used (none selected by default)
3. reload the page

### Do you want to work on this issue?

No

**Comment by neon-mmd** [comment]
Sorry for the late reply.

Thanks :heart: for taking the time reporting this issue. Actually, after doing some tests, it seems to be working on my side. Maybe it looks like an issue with `rate limiting`. So I would suggest increasing the number of allow requests in the config file and let me know if it solves the issue or not :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
@dr460nf1r3 , We are closing this issue as there has not been any activity on this issue for a long time, but if your problem has still not been resolved then we would suggest reopening this issue in the future :slightly_smiling_face: . Also, thanks :heart: again for opening this issue :slightly_smiling_face: .
