### ISSUE TITLE
🔧 Remove the unused mapped ports for docker deployment

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#308]
### What would you like to share?

Remove the unused mapped ports in the `docker compose` file (located under the codebase (`websurfx` directory)), as the search engine can work without it when deployed with docker.

> This change was proposed by `dr410nf1r3` in the issue #271.

The changes to be made in the `docker compose` file is shown below:
``` diff
---
version: "3.9"
services:
  app:
    image: websurfx:latest
    build: .
    ports:
      - 8080:8080
    # Uncomment the following lines if you are using the `hybrid` or `redis` caching feature.
    # depends_on:
    #   - redis
    # links:
    #   - redis
    volumes:
      - ./websurfx/:/etc/xdg/websurfx/
  # Uncomment the following lines if you are using the `hybrid` or `redis` caching feature.
  # redis:
  #   image: redis:latest
- #   ports:
- #     - 6379:6379
```

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you are not familliar with process and add your changes and make a pull request with the changes to this repository and if you are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started contributing :slightly_smiling_face: .  

### Do you want to work on this issue?

None

**Comment by zacharyftw** [comment]
@neon-mmd can you assign me this issue?

**Comment by neon-mmd** [comment]
> @neon-mmd can you assign me this issue?

Yes sure :slightly_smiling_face: . I will assign this issue to you right away :rocket: .

**Comment by zacharyftw** [comment]
https://github.com/neon-mmd/websurfx/pull/309 @neon-mmd i have done it. can you check it up?
