### ISSUE TITLE
✨ `Bing` for the search engine

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#316]
Provide the `bing` search engine for the `websurfx` search engine.  To start working on this issue, you will need to create a new file with the name of the desired engine in the folder `src/engines/` which is located under the codebase (`websurfx` directory). Then in the file, just create a new struct with the name of the engine and then create two `impl` blocks for the struct. One for implementing the `SearchEngine` trait on it and the other for implementing the `parsers` to be used for aggregating results.

After that, just put the name of the desired engine in the match statement located [here,](https://github.com/neon-mmd/websurfx/blob/40b7e6d2ea7cf940d361dc1f9e1c068d19af2f9d/src/models/engine_models.rs#L144) make sure that the name of engine is in lowercase. 

After that, just move to the config file which is located at `websurfx/` directory under the code base and then just edit the config file by including the name of the search engine [here](https://github.com/neon-mmd/websurfx/blob/40b7e6d2ea7cf940d361dc1f9e1c068d19af2f9d/websurfx/config.lua#L52).  

> **Note**
> The engine name to be included in the config file is `not case sensitive` but we would still recommend naming it with the camelcase naming convention.

After doing all the fore-mentioned steps, then we would suggest doing a thorough test to make sure everything works as intended and then submitting a PR.

**Comment by chungquantin** [comment]
I can handle this issue. Plan: will follow DuckDuckGo implementation and replace with the query string of Bing: https://www.bing.com/search?q=%s

**Comment by neon-mmd** [comment]
> I can handle this issue. Plan: will follow DuckDuckGo implementation and replace with the query string of Bing: https://www.bing.com/search?q=%s

Ok, sure :slightly_smiling_face: , I will assign this issue to you right away :rocket: .

**Comment by alamin655** [comment]
@neon-mmd I am taking up this issue as there hasn't been any PR by @chungquantin

**Comment by neon-mmd** [comment]
> @neon-mmd I am taking up this issue as there hasn't been any PR by @chungquantin

I think since chunquantin has been previously been assigned this issue and changquantin might still be working on this issue. Therefore, I would suggest leaving this issue assigned to chungquantin. But if you still want to work on adding more upstream search engines then I would suggest working on the issues related to other search engines. :slightly_smiling_face:

**Comment by neon-mmd** [comment]
chungquantin, it has been one week so far, any progress on this issue so far? We would like to know :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
Chungquantin, it has been nearly a month, any progress on this issue so far? We would like to know :slightly_smiling_face: .

**Comment by jfvillablanca** [comment]
pls assign this to me. thank you

**Comment by neon-mmd** [comment]
> pls assign this to me. thank you

We would be glad to assign this issue to you but we would like to suggest first completing the previous issue because if you assign other issues while not completing the previous ones it blocks others who might be willing to work on this issue which is not good as you know. :slightly_smiling_face:

**Comment by neon-mmd** [comment]
Since you have finished the previous issues, no one has requested to work on it, and you had requested to work on this issue earlier. So we will assign this issue to you. You may start working on it right away :rocket: :slightly_smiling_face: .
