### ISSUE TITLE
🔧 Restrict/Conceal the visibility of the `user-agent` helper module 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#330]
### What would you like to share?

Restrict/Conceal the visibility of the `user-agent` helper module by removing the `pub` keyword in the `mod.rs` file located in `src/results/` directory under the codebase (`websurfx` directory).

The changes to be made in the `mod.rs` are shown below:
``` diff
//! This module provides modules that handle the functionality to aggregate the fetched search
//! results from the upstream search engines and filters it if safe search is set to 3 or 4. Also,
//! provides various models to aggregate search results into a standardized form.

pub mod aggregator;
- pub mod user_agent;
+ mod user_agent;
```

> **Note**
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you are not familliar with process and add your changes and make a pull request with the changes to this repository and if you are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started contributing :slightly_smiling_face: .

### Do you want to work on this issue?

None

**Comment by UdaySagar-Git** [comment]
hey @neon-mmd I want to work on this, can you please assign it to me

**Comment by neon-mmd** [comment]
> hey @neon-mmd I want to work on this, can you please assign it to me

Ok, sure :slightly_smiling_face: , I will assign this issue to you right away :rocket: .
