### ISSUE TITLE
🐛 Unable to deploy the project on `portainer` using docker compose

### ISSUE THREAD

**Issue by Tiritibambix** [neon-mmd/websurfx#342]
### Description

Hello, I'm using the [provided docker-compose](https://github.com/neon-mmd/websurfx/blob/rolling/dev.docker-compose.yml) to run a stack in portainer.
I just changed the port `8080:8080` as I am already using it and added `neonmmd/` in the image name so I can reach it because otherwise it can't find the image:

```
version: "3.9"
services:
  app:
    image: neonmmd/websurfx:latest
    build: .
    ports:
      - 2085:8080
    # Uncomment the following lines if you are using the `hybrid` or `redis` caching feature.
    depends_on:
       - redis
    links:
       - redis
    volumes:
      - /srv/.../Files/Websurfx/:/etc/xdg/websurfx/
  # Uncomment the following lines if you are using the `hybrid` or `redis` caching feature.
  redis:
     image: redis:latest
```

I manage to deploy the stack, but I get an error from the app:
```
2023-10-19T20:31:02.080869632Z thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "Config file/folder not found!!" }', src/bin/websurfx.rs:32:39

2023-10-19T20:31:02.080909251Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Can you hel pme understand this please ?

### Do you want to work on this issue?

No

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to reporting this bug. We really appreciate it :+1: . as it helps improve the project. But I didn't really get the issue, like I would suggest elaborating it. Also, I would recommend providing information about what are you trying to do as well because I see you using the `dev.docker-compose.yml` file instead of the `docker-compose.yml` . So we would like to know whether you are trying to use the docker compose file to deploy it somewhere for production purposes or use it for development purposes ? :slightly_smiling_face:

**Comment by Tiritibambix** [comment]
Thanks for your answer.

I'm just a hobbyist selfhoster.
I was looking for a docker-compose file to quickly deploy and use websurfx. Something that pulls a prebuilt image and runs it in my docker environment.

Is this something possible ?

**Comment by neon-mmd** [comment]
> Thanks for your answer.

You're welcome :bouquet: :slightly_smiling_face: .

> I'm just a hobbyist selfhoster. I was looking for a docker-compose file to quickly deploy and use websurfx. Something that pulls a prebuilt image and runs it in my docker environment.
> 
> Is this something possible ?

Yes sure :slightly_smiling_face: , we do provide a docker compose file for production use in our codebase and as such I would suggest using this docker-compose file here:

 https://github.com/neon-mmd/websurfx/blob/rolling/docker-compose.yml 

Also, if you want to use an official prebuilt image, then I would suggest following this section of the `Websurfx` documentation here:

https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#docker-deployment

Also, if you would like to know what are the pros and cons of each of the features, then I would suggest going through this documentation page as well :slightly_smiling_face: :

https://github.com/neon-mmd/websurfx/blob/rolling/docs/features.md

**Comment by Tiritibambix** [comment]
Thank you so much, and thank you for editing the title. I wasn't able to do it.

https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#prebuild

This is what I was looking for.
I'll try and report back next week.

**Comment by neon-mmd** [comment]
> Thank you so much, and thank you for editing the title. I wasn't able to do it.
> 
> https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md#prebuild
> 
> This is what I was looking for. I'll try and report back next week.

Ok sure :slightly_smiling_face: , no problem, if you face any issue or problem let us know here. We would be glad to help. Also, if you have solved the issue then feel free to report it here and close this issue. :slightly_smiling_face:

**Comment by 0xle0ne** [comment]
Hey @tiritibambix the error you get is most likely because you don't have a config file inside your directory:
`/srv/.../Files/Websurfx/`

You need a `config.lua` with this content:

```lua
-- ### General ###
logging = true -- an option to enable or disable logs.
debug = false -- an option to enable or disable debug mode.
threads = 8 -- the amount of threads that the app will use to run (the value should be greater than 0).

-- ### Server ###
port = "8080" -- port on which server should be launched
binding_ip = "0.0.0.0" --ip address on the which server should be launched.
production_use = true -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
-- if production_use is set to true
-- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
request_timeout = 30 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).
rate_limiter = {
	number_of_requests = 20, -- The number of request that are allowed within a provided time limit.
	time_limit = 3, -- The time limit in which the quantity of requests that should be accepted.
}

-- ### Search ###
-- Filter results based on different levels. The levels provided are:
-- {{
-- 0 - None
-- 1 - Low
-- 2 - Moderate
-- 3 - High
-- 4 - Aggressive
-- }}
safe_search = 2

-- ### Website ###
-- The different colorschemes provided are:
-- {{
-- catppuccin-mocha
-- dark-chocolate
-- dracula
-- gruvbox-dark
-- monokai
-- nord
-- oceanic-next
-- one-dark
-- solarized-dark
-- solarized-light
-- tokyo-night
-- tomorrow-night
-- }}
colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
theme = "simple" -- the theme name which should be used for the website

-- ### Caching ###
redis_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.

-- ### Search Engines ###
upstream_search_engines = {
	DuckDuckGo = true,
	Searx = false,
} -- select the upstream search engines from which the results should be fetched.
```

Also if you like to selfhost stuff i would suggest to take a look at [Nanocl](https://github.com/nxthat/nanocl) instead of using docker compose

**Comment by neon-mmd** [comment]
> Hey @tiritibambix the error you get is most likely because you don't have a config file inside your directory: `/srv/.../Files/Websurfx/`
> 
> You need a `config.lua` with this content:
> 
> ```lua
> -- ### General ###
> logging = true -- an option to enable or disable logs.
> debug = false -- an option to enable or disable debug mode.
> threads = 8 -- the amount of threads that the app will use to run (the value should be greater than 0).
> 
> -- ### Server ###
> port = "8080" -- port on which server should be launched
> binding_ip = "0.0.0.0" --ip address on the which server should be launched.
> production_use = true -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
> -- if production_use is set to true
> -- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
> request_timeout = 30 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).
> rate_limiter = {
> 	number_of_requests = 20, -- The number of request that are allowed within a provided time limit.
> 	time_limit = 3, -- The time limit in which the quantity of requests that should be accepted.
> }
> 
> -- ### Search ###
> -- Filter results based on different levels. The levels provided are:
> -- {{
> -- 0 - None
> -- 1 - Low
> -- 2 - Moderate
> -- 3 - High
> -- 4 - Aggressive
> -- }}
> safe_search = 2
> 
> -- ### Website ###
> -- The different colorschemes provided are:
> -- {{
> -- catppuccin-mocha
> -- dark-chocolate
> -- dracula
> -- gruvbox-dark
> -- monokai
> -- nord
> -- oceanic-next
> -- one-dark
> -- solarized-dark
> -- solarized-light
> -- tokyo-night
> -- tomorrow-night
> -- }}
> colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
> theme = "simple" -- the theme name which should be used for the website
> 
> -- ### Caching ###
> redis_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.
> 
> -- ### Search Engines ###
> upstream_search_engines = {
> 	DuckDuckGo = true,
> 	Searx = false,
> } -- select the upstream search engines from which the results should be fetched.
> ```
> 
> Also if you like to selfhost stuff i would suggest to take a look at [Nanocl](https://github.com/nxthat/nanocl) instead of using docker compose

Leon3s, thanks ❤️  for your cool suggestion. After looking into this option. I think both the options are good the `docker-compose` one and the one you suggested. I think I would leave the option to use either one of them on tiritibambix.

Also, if you don't mind, would you like to provide a seperate section in the [`installation`](https://github.com/neon-mmd/websurfx/blob/rolling/docs/installation.md) docs about deploying websurfx using nanocl ?. Because I think having more options would be better. 🙂

**Comment by Tiritibambix** [comment]
So I finally had time to try again, and I follow your instructions @leon3s @neon-mmd . Thanks again for that.

So I created the folder `/srv/Files/Websurfx/` in which I created two new empty files named allowlist.txt and blocklist.txt. Finally, I created a new config file `config.lua` with this configuration:
```
-- ### General ###
logging = true -- an option to enable or disable logs.
debug = false -- an option to enable or disable debug mode.
threads = 8 -- the amount of threads that the app will use to run (the value should be greater than 0).

-- ### Server ###
port = "8080" -- port on which server should be launched
binding_ip = "0.0.0.0" --ip address of the machine running websurfx
production_use = false -- whether to use production mode or not (in other words this option should be used if it is to be used to host it on the server to provide a service to a large number of users (more than one))
-- if production_use is set to true
-- There will be a random delay before sending the request to the search engines, this is to prevent DDoSing the upstream search engines from a large number of simultaneous requests.
request_timeout = 30 -- timeout for the search requests sent to the upstream search engines to be fetched (value in seconds).
rate_limiter = {
	number_of_requests = 20, -- The number of request that are allowed within a provided time limit.
	time_limit = 3, -- The time limit in which the quantity of requests that should be accepted.
}

-- ### Search ###
-- Filter results based on different levels. The levels provided are:
-- {{
-- 0 - None
-- 1 - Low
-- 2 - Moderate
-- 3 - High
-- 4 - Aggressive
-- }}
safe_search = 2

-- ### Website ###
-- The different colorschemes provided are:
-- {{
-- catppuccin-mocha
-- dark-chocolate
-- dracula
-- gruvbox-dark
-- monokai
-- nord
-- oceanic-next
-- one-dark
-- solarized-dark
-- solarized-light
-- tokyo-night
-- tomorrow-night
-- }}
colorscheme = "catppuccin-mocha" -- the colorscheme name which should be used for the website theme
theme = "simple" -- the theme name which should be used for the website

-- ### Caching ###
redis_url = "redis://redis:6379" -- redis connection url address on which the client should connect on.

-- ### Search Engines ###
upstream_search_engines = {
	DuckDuckGo = true,
	Searx = false,
} -- select the upstream search engines from which the results should be fetched.
```
Then, I went to portainer and pasted this docker-compose in the "stack" window:
```
---
version: '3.9'
services:
  app:
    image: neonmmd/websurfx:latest
    ports:
      - 8080:8080
    volumes:
      - /srv/Files/Websurfx:/etc/xdg/websurfx/
```
Now I get this error:
```
[2023-10-25T19:05:11Z INFO  websurfx::cache::cacher] Using a hybrid cache

thread 'main' panicked at 'Redis cache configured: failed to lookup address information: Name or service not known', /app/src/cache/cacher.rs:50:22

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
--------------------------------------------
So I tried
```
---
version: '3.9'
services:
  app:
     image: neonmmd/websurfx:redis
     ports:
      - 8080:8080
     depends_on:
      - redis
     links:
      - redis
     volumes:
      - /srv/Files/Websurfx:/etc/xdg/websurfx/
  redis:
     image: redis:latest
```
Now it's working.

Thanks for your help.
