### ISSUE TITLE
📝 Typo correction and Grammatical in the `features` and `installation` documentation page

### ISSUE THREAD

**Issue by btwshivam** [neon-mmd/websurfx#354]
### Description

Wanted to fix all the Typo corrections and Grammatical in the features.md and installation.md documentation page.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to open this issue. We really appreciate it :+1:  as it helps improve our project. 

> Wanted to fix all the Typo corrections and Grammatical in the features.md and installation.md documentation page.

Yes sure :slightly_smiling_face: , I will assign this issue to you right away :rocket: .
