### ISSUE TITLE
📝 Typo correction and Grammatical correction in the `developing.md` documentation page

### ISSUE THREAD

**Issue by btwshivam** [neon-mmd/websurfx#356]
### Description

Wanted to fix all the Typo corrections and Grammatical corrections in the `developing` documentation page

### Do you want to work on this issue?

None

**Comment by neon-mmd** [comment]
> Wanted to fix all the Typo corrections and Grammatical corrections in the <developing.md> documentation page

Yes, sure, I will assign this issue to you right away :rocket: :slightly_smiling_face: .
