### ISSUE TITLE
Create a settings page to allow users to select the search engines from the UI

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#36]
Create an Ui to select different configuration options like themes, colorschemes and different engines to choose from with the help of checkboxes and also provide a `select all` and `deselect all` button to select/deselect all engines at once.

**Comment by sam-sunder** [comment]
@neon-mmd  can you list in more detail that what settings to be added

**Comment by neon-mmd** [comment]
> @neon-mmd can you list in more detail what settings to be added

Yes sure :slightly_smiling_face: , Here is the list of options that I want to have on the settings page:
- [x] An option to allow users to choose different themes from the UI.
- [x] An option to allow users to choose different colorschemes from the UI.
- [x] An option to select/unselect different upstream engines (I feel checkboxes would be better for these).
- [x] A button `select all` or a checkbox to select all the engines in the list.
- [x] Similarly a button `deselect all` or checkbox to deselect all the engines in the list.

I provided this list as a checklist because I feel this will make it easier for you to track the progress of the changes you make :slightly_smiling_face: .

Also, note @bcsamrudh is also working on this issue so if you wish you can work in collaboration with him :slightly_smiling_face:, also if you have any ideas or want to discuss you can do it here by either opening an issue or over on our Discord server :slightly_smiling_face: .

**Comment by sam-sunder** [comment]
@neon-mmd This is only frontend. It send data via POST request to `/settings` when save is clicked and further part needs to be developed on server side.
