### ISSUE TITLE
🐛 Search results are no longer being cached in the `websurfx` search engine

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#382]
### Description

After thorough testing, we have noticed that the search results are no longer being cached by both implementation of the caches the In-memory and Redis caching. After debugging the app, we receive two errors when the app tries to cache the results with both of them. The first, when the app tries to cache the result with Redis server, we receive an error stating something like `The response type is not of a valid string type`. Second, when the app tries to cache/retrieve results with the In-memory cache (mini-mocha), we get an error stating something like `The cache is missing the value`. 

### Do you want to work on this issue?

No

**Comment by neon-mmd** [comment]
@gzsombor would you like to work on this issue? We have suggested your name because we think you might have a better idea on this issue. :slightly_smiling_face:

**Comment by ashwinvin** [comment]
Hey! I would like to work on this.

**Comment by neon-mmd** [comment]
> Hey! I would like to work on this.

Yes, sure :slightly_smiling_face: , I would assign this issue to you right away :rocket: . You may start working on it now :slightly_smiling_face:
