### ISSUE TITLE
✨ Ranking of aggregated search results based on relevancy of the search result to the user's search query

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#393]
### Description

Implement an algorithm to rank (in other words, sort) the aggregated search results according to the relevancy of the search result based on the user's search query by analyzing three properties of the search results: 
- The search result's tile
- description
- and URL.

Also, checking each of the properties for how closely they are related if they are too closely related then it should be the first result in all search results. If it is least related, then it should be the last result to be shown in all the search results.

The algorithm should be implemented in the `aggregator.rs` file located in the `src/results/` folder under the codebase (`websurfx` directory) where the algorithm to aggregate search results lie.

### Do you want to work on this issue?

None

**Comment by neon-mmd** [comment]
@xffxff would you like to work on this issue? We have suggested your name because we think you might have a better idea on this issue. 🙂

**Comment by cjtorralba** [comment]
Checking out what I can do with this currently

**Comment by neon-mmd** [comment]
> Checking out what I can do with this currently

Yes sure :slightly_smiling_face: , I will assign this issue to you right away :rocket: .

**Comment by spencerjibz** [comment]
Assign that issue to me

**Comment by neon-mmd** [comment]
> Assign that issue to me

Yes sure, we will assign this issue to you as well. You may start collaborating with cjtorralba right away :rocket: :slightly_smiling_face: .
