### ISSUE TITLE
👷 GitHub action to automate release based on semantic versioning

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#400]
### What would you like to share?

Provide a GitHub action to automate the release of a new release of the project when a new PR is merged in using conventional commit messages. 

**Note:** The release versions should follow the [semantic versioning](https://semver.org/spec/v2.0.0.html) style of versioning.

### Do you want to work on this issue?

None

### Additional information

Reference:
- [A video showing a project using conventional commits to automate releases](https://piped.kavin.rocks/watch?v=fcHJZ4pMzBs)

**Comment by scottc943** [comment]
I am currently working on this issue

**Comment by neon-mmd** [comment]
> I am currently working on this issue

Yes sure, we will assign this issue to you. You may start working on it right away :rocket: :slightly_smiling_face:
