### ISSUE TITLE
💄 Redesign the `websurfx` logo for better understandability

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#404]
### What would you like to share?

Redesign the Websurfx logo by adding the letter W back in the logo to make understanding the logo easier by removing confusion associated with interpreting the ship symbol.

### Do you want to work on this issue?

None

**Comment by lxrst** [comment]
+1
A transparent version on the web UI would be great too.

**Comment by cybrejon** [comment]
Working on it
