### ISSUE TITLE
Add format checking to the CI job?

### ISSUE THREAD

**Issue by XFFXFF** [neon-mmd/websurfx#41]
We currently don't verify formatting in our CI jobs, but perhaps it would be beneficial to incorporate this into our CI jobs

**Comment by neon-mmd** [comment]
We already have this GitHub action it is available as a `rust_format.yml` under the path `.github/workflows/` and it runs 2 things, a `clippy` check, and a `rustfmt` check. but if you wish to we can separate this into two separate GitHub actions, What do you say @XFFXFF ?? Should we separate it??

**Comment by XFFXFF** [comment]
> We already have this GitHub action it is available as a `rust_format.yml` under the path `.github/workflows/` and it runs 2 things, a `clippy` check, and a `rustfmt` check.

@neon-mmd  Yes, we do have a CI job named `Rust format and Clippy checks`, but it only installs `rustfmt` and `clippy` without actually using them. You can refer to the [log](https://github.com/neon-mmd/websurfx/actions/runs/5040772935/jobs/9039853432?pr=40) of this job to confirm this

**Comment by neon-mmd** [comment]
> @neon-mmd Yes, we do have a CI job named `Rust format and Clippy checks`, but it only installs `rustfmt` and `clippy` without actually using them. You can refer to the [log](https://github.com/neon-mmd/websurfx/actions/runs/5040772935/jobs/9039853432?pr=40) of this job to confirm this

Yes, you are right :smile: . After reading the logs I understood my mistake, my bad but thanks for pointing it out and fixing it :slightly_smiling_face: .

**Comment by neon-mmd** [comment]
This issue has been taken care of by PR https://github.com/neon-mmd/websurfx/pull/49, so, therefore, I mark this issue as completed :slightly_smiling_face: .
