### ISSUE TITLE
✨ Compression and encryption for the cached search results

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#416]
#### Proposal of the Changes

Provide compression, encryption and both for the search results that are going to be a part of the cache by using the rust's feature/conditional based compilation feature. 

The three features should look something this: 
- `Default`: No compression and encryption
- `Compress-cache-results:`  Uses compression algorithm like `brotli` (which is considered good for text based compression)
- `Encrypt-cache-results:` Uses an encryption algorithm like `chacha20poly1305` (which is considered very strong encryption and is widely adopted in the `rust` programming language). Also, the generated encryption should change on each restart of the `websurfx` server, which help against attacks and improve the privacy of the user. 
-  `cec-cache-results:` Uses both compression and encryption to first compress the results then encrypt it and then compress it back again to get the advantages of both encryption and compression. 

### Do you want to work on this issue?

None

#### The Reason Behind the Proposal

The reasoning behind the changes are as follows : 
- By compressing cache results, this can help reduce the amount of memory used for storing the cache results. Second, it can help improve the speed of transferring cache results over the internet. The size of the cache results become smaller after compression. So, if the cache results were to be stored on a Redis server provided by a VPS provider.
- By encrypting cache results, this can help improve user privacy by not allowing the Redis VPS provider to know what is being cached on their Redis server. Though, the cache results size become larger after encryption.
- By using both the encryption and compression with `cec-cache-results` feature, we provide the advantages of both compression and encryption by first compressing the results and the encrypting it. Then compressing it again so that the size of the cache result remains nearly the same as it was after the first compression.

#### Sample Code

Here is the sample which provides a general idea of what should be used to implement the above discussed features:

``` rust
use base64::Engine;
use chacha20::{
    cipher::{
        generic_array::GenericArray,
        typenum::{UInt, UTerm},
        StreamCipherCoreWrapper,
    },
    ChaChaCore,
};
use chacha20poly1305::{
    aead::Aead,
    aead::OsRng,
    consts::{B0, B1},
    AeadCore, ChaCha20Poly1305, ChaChaPoly1305, KeyInit,
};
use std::{io::Write, sync::OnceLock};

static CIPHER: OnceLock<
    ChaChaPoly1305<
        StreamCipherCoreWrapper<ChaChaCore<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B1>, B0>>>,
    >,
> = OnceLock::new();

static ENCRYPTION_KEY: OnceLock<GenericArray<u8, UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>, B0>>> =
    OnceLock::new();

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let some_content = r#"
{
	"random": "20",
	"random float": "19.309",
	"bool": "true",
	"date": "1996-10-14",
	"regEx": "hellooooo to you",
	"enum": "online",
	"firstname": "Dorthy",
	"lastname": "Dreda",
	"city": "Forked River",
	"country": "Germany",
	"countryCode": "ZW",
	"email uses current data": "Dorthy.Dreda@gmail.com",
	"email from expression": "Dorthy.Dreda@yopmail.com",
	"array": [
		"Quintina",
		"Courtnay",
		"Ida",
		"Chloris",
		"Regina"
	],
	"array of objects": [
		{
			"index": "0",
			"index start at 5": "5"
		},
		{
			"index": "1",
			"index start at 5": "6"
		},
		{
			"index": "2",
			"index start at 5": "7"
		}
	],
	"Elka": {
		"age": "39"
	}
}
    "#;

    let mut writer = brotli::CompressorWriter::new(Vec::new(), 4096, 11, 22);
    writer.write_all(some_content.as_bytes())?;
    let something = writer.into_inner();

    let cipher = CIPHER.get_or_init(|| {
        let key = ChaCha20Poly1305::generate_key(&mut OsRng);
        ChaCha20Poly1305::new(&key)
    });

    let encryption_key = ENCRYPTION_KEY.get_or_init(
        || ChaCha20Poly1305::generate_nonce(&mut OsRng), // 96-bits; unique per message
    );

    let ciphertext = cipher
        .encrypt(&encryption_key, something.as_slice())
        .unwrap();

    let mut writer = brotli::CompressorWriter::new(Vec::new(), 4096, 11, 22);
    writer.write_all(ciphertext.as_slice())?;
    let something_diff_2 = writer.into_inner();

    let something_diff_3 =
        base64::engine::general_purpose::STANDARD_NO_PAD.encode(something_diff_2.clone());

    println!("output (original): {}", some_content.as_bytes().len());
    println!("output (first compression): {}", something.len());
    println!("output (encryption): {}", ciphertext.len());
    println!("output (second compression): {:?}", something_diff_2.len());
    println!("output (base64): {}", something_diff_3.len());

    Ok(())
}
```

**Output of the sample code**

``` shell
output (original): 656
output (first compression): 304
output (encryption): 320
output (second compression): 324
output (base64): 459
```

**dependencies section of the Cargo.toml file of the sample code**

``` toml
[dependencies]
brotli = { version = "3.4.0", default-features = false, features=["std"] }
chacha20poly1305={version="0.10.1", default-features=false, features=["alloc","getrandom"]}
chacha20 = {version="0.9.1", default-features=false}
base64 = {version="0.21.5", default-features=false, features=["std"]}
```

**Comment by evanyang1** [comment]
I am going to give this a shot

**Comment by neon-mmd** [comment]
> I am going to give this a shot

Ok sure, we will assign this issue to you right away :rocket: :slightly_smiling_face: .

**Comment by ibnz36** [comment]
Ok, I think this is viable, and wouldn't be that much of a deal to implement. Some places where this is an easy add-on is [here](https://github.com/neon-mmd/websurfx/blob/67c3e39d4e421e408f9a7876f07ede2e0e41eb26/src/cache/cacher.rs#L110C30-L110C43) (replace SearchResults with a String and use a JSON similar to redis cache's) and [here](https://github.com/neon-mmd/websurfx/blob/67c3e39d4e421e408f9a7876f07ede2e0e41eb26/src/cache/redis_cacher.rs#L69).

**Comment by neon-mmd** [comment]
> Ok, I think this is viable, and wouldn't be that much of a deal to implement. Some places where this is an easy add-on is [here](https://github.com/neon-mmd/websurfx/blob/67c3e39d4e421e408f9a7876f07ede2e0e41eb26/src/cache/cacher.rs#L110C30-L110C43) (replace SearchResults with a String and use a JSON similar to redis cache's) and [here](https://github.com/neon-mmd/websurfx/blob/67c3e39d4e421e408f9a7876f07ede2e0e41eb26/src/cache/redis_cacher.rs#L69).

Ok thanks :heart:  for the suggestion. We really appreciate it :+1: . Also, we have assigned this issue to you too :slightly_smiling_face:

**Comment by spencerjibz** [comment]
Hi, happy to help out with that issue too.

**Comment by neon-mmd** [comment]
> Hi, happy to help out with that issue too.

Ok sure, we have assigned to you, you may start working togather right away :rocket: :slightly_smiling_face:

**Comment by evanyang1** [comment]
Really appreciate the help. I'm reading the code. Any hints are welcome.
