### ISSUE TITLE
📝 New `websurfx` logo for the `readme` 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#420]
### Description

Replace the old `websurfx` in the `readme` file located under the codebase (`websurfx` directory) with the new `websurfx` logo proposed in the PR #418 by replacing the logo image file in the `images` folder under the codebase (`websurfx` directory). Also, replace the image name in the `readme` file.   

### Do you want to work on this issue?

None

**Comment by cybrejon** [comment]
id like to work on this

**Comment by neon-mmd** [comment]
> id like to work on this

Yes sure :slightly_smiling_face: , I will assign this issue to you right away :rocket: .
