### ISSUE TITLE
💄 Redesign the theme design for the `about` page

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#433]
### What would you like to share?

Redesign the `simple` theme design for the `about` page for the search engine. To improve the design of the `simple` theme design for the `about` page. You will need to edit the code for the about page present in the `simple.css` file located in the `public/static/themes` folder located under the codebase (`websurfx` directory).

### Do you want to work on this issue?

None

**Comment by cybrejon** [comment]
id like to work on this

**Comment by neon-mmd** [comment]
> id like to work on this

Yes sure, we will assign this issue to you right away :rocket: :slightly_smiling_face: .

**Comment by s1819261** [comment]
hi! i'd like to work on this issue :)

**Comment by neon-mmd** [comment]
> hi! i'd like to work on this issue :)

Yes sure, I will assign this issue to you right away :rocket: :slightly_smiling_face:
