### ISSUE TITLE
🐛 Clicked Title Becomes Invisible on Web Page

### ISSUE THREAD

**Issue by xffxff** [neon-mmd/websurfx#440]
### Description

When clicking on a title in the search results, the title becomes invisible, making it impossible for users to read the text.

### Screenshots

![image](https://github.com/neon-mmd/websurfx/assets/30254428/ef42b3a3-bb42-4565-ac74-b8f1c4897cd6)

### Do you want to work on this issue?

None

**Comment by alamin655** [comment]
![Screenshot (25)](https://github.com/neon-mmd/websurfx/assets/129589283/6bd805f0-d87b-4b21-b73b-270abe7be471)
![Screenshot 2023-12-13 191425](https://github.com/neon-mmd/websurfx/assets/129589283/673ebc9a-99c8-4ca8-b21d-4aa5251793ec)
It's the black result title, which has become invisible now due to the recent theme change.

**Comment by neon-mmd** [comment]
Thanks :heart: for taking the time to reporting this issue. We really appreciate it :+1: as it helps improve our project :slightly_smiling_face: . 

Ok, according to you and alamin655, I tried to reproduce this error on my system, but I don't seem to reproduce it. I tried visiting the URL from the search results and reloading the same page again, but I am still able to see the titles in the results page (screenshot attached below). So I would suggest maybe could you provide me with more details like what you did before getting this issue like did you click on the link or anything else? Also, could you also provide information on what kind of web browser you are using to query the search engine? (Like I am using the brave browser on my side to query the search engine)  :slightly_smiling_face: 

![image](https://github.com/neon-mmd/websurfx/assets/132049916/ff6c67de-9bba-4964-8489-8ba31f7647a4)

**Comment by xffxff** [comment]
Here's the information about my environment:

* OS: macOS
* Browser: Edge

**Comment by xffxff** [comment]
![image](https://github.com/neon-mmd/websurfx/assets/30254428/4ebeea41-b5f0-493a-877d-4f2e8bad1402)

After further investigation, I've identified a potential cause for the invisible title issue. It seems to be related to the CSS styling for visited links within the search results. Here's the specific style rule that appears to be causing this problem:
```css
results_aggregated .result h1 a:visited {
    color: var(--background-color);
}
```

**Comment by neon-mmd** [comment]
> ![image](https://private-user-images.githubusercontent.com/30254428/290460754-4ebeea41-b5f0-493a-877d-4f2e8bad1402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTU1ODYsIm5iZiI6MTcwMjU1NTI4NiwicGF0aCI6Ii8zMDI1NDQyOC8yOTA0NjA3NTQtNGViZWVhNDEtYjVmMC00OTNhLTg3N2QtNGYyZThiYWQxNDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEyMDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NDAwZGRiODJmYjZhNjNiZDI2YTNkYWQxODE2MjQzNjU4NGMxYTU5MTYzNGZkMWQzMTVkNjg1NGMwNmJlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wFQkFnLjQ9MG6wEuTALTEMFBQDs8fTho4bdDeW7GVc)
> 
> After further investigation, I've identified a potential cause for the invisible title issue. It seems to be related to the CSS styling for visited links within the search results. Here's the specific style rule that appears to be causing this problem:
> 
> ```css
> results_aggregated .result h1 a:visited {
>     color: var(--background-color);
> }
> ```

Thanks :heart: for pointing it out, I was finally able to reproduce the issue by not querying the search engine in incognito mode and I stumbled across the same issue. I think we will fix this issue as soon as possible by using a different color for the visited property of the links. :slightly_smiling_face:
