### ISSUE TITLE
🧑‍💻 Install `cargo-watch` via the `nix develop` command

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#447]
#### Work Expected From This Issue
Provide the `cargo-watch` package via the `nix develop` command by adding the `cargo-watch` installation step in the `mkShell.buildInputs` of the nix flake.

#### Reason Behind the Change
The reason behind the change is to improve the developer experience by automating the installation of the `cargo-watch` package via the `nix develop` command for the nix package manager users.

### Do you want to work on this issue?

None

**Comment by jfvillablanca** [comment]
i'll work on this, can you assign this to me :)
i also noticed that there are multiple things that should also be included in `mkShell.buildInputs` such as `rustfmt` and `rust-analyzer` among other things. I'll also try to update the docs to reflect on how to get started contributing to the project if using NixOS

**Comment by neon-mmd** [comment]
> i'll work on this, can you assign this to me :) i also noticed that there are multiple things that should also be included in `mkShell.buildInputs` such as `rustfmt` and `rust-analyzer` among other things. I'll also try to update the docs to reflect on how to get started contributing to the project if using NixOS

Yes sure, I will assign this issue to you right away :rocket:  :slightly_smiling_face: .
