### ISSUE TITLE
🐛 `Cargo test` failure when developing work on the app using `nix develop` due to missing `openssl` package

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#448]
### Description

Provide a fix for the `cargo test` failure issue by providing a way to install the `openssl` package prior to running the command in the nix flake.

### Do you want to work on this issue?

None

**Comment by jfvillablanca** [comment]
Will fix this 😀

**Comment by neon-mmd** [comment]
> Will fix this 😀

Yes sure, I will assign this issue to you right away :rocket: :slightly_smiling_face: .
