### ISSUE TITLE
💄 Replace the search button with a magnifying glass

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#450]
#### Work Expected From the Issue
Replace the search button in the search page and the homepage with a magnifying glass.

#### Reason Behind the Change
Improve the search engine UI, making it look more modern and appealing to the user. Thus improving the user experience.

### Do you want to work on this issue?

None

**Comment by loikx** [comment]
Hello, @neon-mmd, I'd like to work on this issue. Can I use any magnifying glass .svg image, that I like?

**Comment by neon-mmd** [comment]
> Hello, @neon-mmd, I'd like to work on this issue. 

Yes sure, we will assign this issue to you right away :rocket: :slightly_smiling_face: .

> Can I use any magnifying glass .svg image, that I like?

Yes, we would suggest using any magnifying glass svg image but make sure to select such an image that actually looks good on all colorschemes like it should not look bad or invisible or does not have a high contrast. Also, you can discuss about the images you choose on the project's discord server (link of the discord can be found on the project readme) if you free comfortable and if you wish to. :slightly_smiling_face: 

Also, we would suggest that if you find no such images that looks good on all colorschemes then you can also put the svg image in the HTML itself and change the color using the `fillproperty` attribute. 

Moreover, when you add the image in the HTML code itself then we would suggest going through this docs on the `maud` HTML framework which covers everything to write maud HTML code.

Here is the link to the `muad` docs:

https://maud.lambda.xyz
