### ISSUE TITLE
📝 NixOS development environment setup

### ISSUE THREAD

**Issue by jfvillablanca** [neon-mmd/websurfx#453]
### Description

- The current instructions for setting up a developer environment are suboptimal and are using assumptions that does not work in NixOS.
- For example: `docker`, `rust-analyzer`, `rustfmt` can be included inside `mkShell.buildInputs`. `nodejs` also needs to be added to install dev dependencies such as `stylelint-config-standard` and `postcss-lit` which are used by pre-commit hooks.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Since you have requested to work on this issue. We have assigned this issue to you. You may start working on it right away :rocket: :slightly_smiling_face: .
