### ISSUE TITLE
:bug:  Explicit `Content-Type` header for HTTP response

### ISSUE THREAD

**Issue by maokwen** [neon-mmd/websurfx#456]
### What would you like to share?

I'm using a cloudflare tunnel to connect my websurfx instance by HTTPS.
When I open the `/` `/setting` or `/about` path, it returns a plain html file. But `/404` page rendering as normal.
I checked the dev console and source code, find that `content_type` response header is not set by default.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Since you have requested to work on this issue. So we will assign this issue to you. You may start working on it right away :rocket: :slightly_smiling_face: .
