### ISSUE TITLE
:recycle:  The page number for upstream search queries should start at 0

### ISSUE THREAD

**Issue by greengeckoz** [neon-mmd/websurfx#459]
### Description

The back-end starts the page number count at 1 and has different code for upstream search engines to handle page 1 and 0. Changing the back end to start at 0 instead will help keep the design and implementations consistent.

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
Since you have requested to work on this issue. So we will assign this issue to you. You may start working on it right away :rocket: :slightly_smiling_face: .
