### ISSUE TITLE
🐛 Results from different search engines get cached as the same key

### ISSUE THREAD

**Issue by greengeckoz** [neon-mmd/websurfx#463]
### Description

If the user changes their settings to use different search engines and repeats a search they already made, the cache will incorrectly return the old results instead of doing a new search with the new selected engines. 

The cache uses the URL as a key to lookup and store the search results, so the URL will have to be modified to reflect which search engines were used.

### Do you want to work on this issue?

None

**Comment by greengeckoz** [comment]
I'll claim this issue.

**Comment by neon-mmd** [comment]
> I'll claim this issue.

Yes sure, I will assign this issue to you. You may start working on it right away :rocket: :slightly_smiling_face: .
