### ISSUE TITLE
Should we move the documentation from the wiki section to the "docs" folder in the codebase??

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#47]
I think having the documentation under the wiki section makes it go unnoticed most of the time because of that sometimes it remains out of sync with the changes that are being made which is bad as you know so I feel having it under the `docs` folder will make it more noticeable. What do you say @XFFXFF @alamin655 ??.

**Comment by XFFXFF** [comment]
I tend to move the documentation to the `docs` folder. To be honest, I haven't even accessed the wiki section yet.

**Comment by alamin655** [comment]
I agree. Moving the documentation to a `docs` folder would make it more visible and help keep it up to date.

**Comment by neon-mmd** [comment]
Ok then after hearing your suggestions, let's move the documentation from the wiki to the docs folder so that anybody willing to contribute also see the docs also a candidate for contribution :smile: .
