### ISSUE TITLE
🐛 `Librex` engine only returns one result on the search page

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#482]
### Description

Provide a fix for the `Librex` search engine only returns one result on the search page when enabled from the settings page or the config.

### Do you want to work on this issue?

None

**Comment by jf-botto** [comment]
I'd love to work on this if possible?

**Comment by neon-mmd** [comment]
> I'd love to work on this if possible?

Yes sure, we are assigning this issue to you. You may start working on it right away :rocket: :slightly_smiling_face:
