### ISSUE TITLE
🐛 Minification of javascript files fails while running the build command

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#484]
### Description

Recently, due to unknown reasons the minification of javascript files which happens when you set the `PKG_ENV` variable to `prod` and run the `cargo build` command seems to fail with an assertion error. So provide a fix for this issue by investigating the cause of the error and providing the updated code if necessary to fix this issue.

Additionally, The code for the minification of javascript files lies in the `build.rs` file under the codebase (`websurfx` directory).

### Do you want to work on this issue?

None

**Comment by greengeckoz** [comment]
This issue should be fixed as soon as https://github.com/wilsonzlin/minify-js/pull/19 is pulled.

**Comment by neon-mmd** [comment]
> This issue should be fixed as soon as [wilsonzlin/minify-js#19](https://github.com/wilsonzlin/minify-js/pull/19) is pulled.

Since you are working on this issue. So we are assigning the issue to you. Now we would suggest you to continue working on this issue. :slightly_smiling_face:
