### ISSUE TITLE
:recycle: `Json` api support for the upstream search engines

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#485]
#### Work expected from the Issue

Provide support for fetching data from official json api from the upstream search engines. 

For this you will need to provide a new function in the trait `SearchEngine` located in the `src/modals/engine_modals` directory under the codebase (`websurfx` directory) which will return the json data as a bytes slice from the upstream search engine's official api.

#### Reasoning Behind the Issue

Recently, we have found that some engines do not seem to support pagination with the search url parameter and they only support it via their official json api. So, by working on this issue, this will provide support for all those engines as well. Also, it will make contributing more search engines easier which will improve the developer experience.

#### Sample Function Code

Here is a sample of what the function might look like:

```rust
    /// This helper function fetches/requests the json search results from the upstream search engine as bytes.
    ///
    /// # Arguments
    ///
    /// * `url` - It takes the url of the upstream search engine with the user requested search
    /// query appended in the search parameters.
    /// * `header_map` - It takes the http request headers to be sent to the upstream engine in
    /// order to prevent being detected as a bot. It takes the header as a HeaderMap type.
    /// * `request_timeout` - It takes the request timeout value as seconds which is used to limit
    /// the amount of time for each request to remain connected when until the results can be provided
    /// by the upstream engine.
    ///
    /// # Error
    ///
    /// It returns the html data as a bytes slice if the upstream engine provides the data as expected
    /// otherwise it returns a custom `EngineError`.
    async fn fetch_json_as_bytes_from_upstream(
        &self,
        url: &str,
        header_map: reqwest::header::HeaderMap,
        client: &Client,
    ) -> Result<&[u8], EngineError> {
        // fetch the html from upstream search engine
        Ok(client
            .get(url)
            .headers(header_map) // add spoofed headers to emulate human behavior
            .send()
            .await
            .change_context(EngineError::RequestError)?
            .bytes()
            .await
            .change_context(EngineError::RequestError)?)
    }
```

> [!Note]
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you are not familliar with process and add your changes and make a pull request with the changes to this repository and if you are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started contributing :slightly_smiling_face: .

### Do you want to work on this issue?

None

**Comment by jfvillablanca** [comment]
I'd like to work on this since I'll be using this to implement Qwant [#317]

**Comment by neon-mmd** [comment]
> I'd like to work on this since I'll be using this to implement Qwant [#317]

Yes sure, we will assign this issue to you. You may start working on it right away :rocket: :slightly_smiling_face:

**Comment by jfvillablanca** [comment]
Is it okay for the return type to be a `Result<Vec<u8>, EngineError>` instead of `Result<&[u8], EngineError>`

in other words, instead of:

```rust
Ok(client
    .get(url)
    .headers(header_map)
    .send()
    .await
    .change_context(EngineError::RequestError)?
    .bytes() // This returns Bytes causing a compile-time error
    .await
    .change_context(EngineError::RequestError)?)
```

I rewrite it like this:
```rust
Ok(client
    .get(url)
    .headers(header_map)
    .send()
    .await
    .change_context(EngineError::RequestError)?
    .bytes()
    .await
    .change_context(EngineError::RequestError)?
    .to_vec()) // Turn into a Vec instead
```

what do you think? will this be a suboptimal implementation?

**Comment by neon-mmd** [comment]
> Is it okay for the return type to be a `Result<Vec<u8>, EngineError>` instead of `Result<&[u8], EngineError>`
> 
> in other words, instead of:
> 
> ```rust
> Ok(client
>     .get(url)
>     .headers(header_map)
>     .send()
>     .await
>     .change_context(EngineError::RequestError)?
>     .bytes() // This returns Bytes causing a compile-time error
>     .await
>     .change_context(EngineError::RequestError)?)
> ```
> 
> I rewrite it like this:
> 
> ```rust
> Ok(client
>     .get(url)
>     .headers(header_map)
>     .send()
>     .await
>     .change_context(EngineError::RequestError)?
>     .bytes()
>     .await
>     .change_context(EngineError::RequestError)?
>     .to_vec()) // Turn into a Vec instead
> ```
> 
> what do you think? will this be a suboptimal implementation?

Actually, I don't mind both implementations are good, but slices tend to be a little bit more memory efficient, that's why I had put the result with the slices in the sample code. Also, one thing I would like to suggest that is that you don't need to add `to_vec()` because the `.bytes()` function already returns a `vec<u8>` so converting a vec fo a vec does not make sense like it would be an unnecessary conversion and also redundant too. :slightly_smiling_face:

**Comment by jfvillablanca** [comment]
> Also, one thing I would like to suggest that is that you don't need to add `to_vec()` because the `.bytes()` function already returns a `vec<u8>` so converting a vec fo a vec does not make sense like it would be an unnecessary conversion and also redundant too.

Can you clarify this for me because I might be missing something here. Because the compiler advises me to use the `.to_vec()` method. I'm fairly new to the library and the language so please excuse me if I missed something :sweat_smile: 

![2024-01-29_19-00](https://github.com/neon-mmd/websurfx/assets/31008330/f741cc9d-5c3f-4ba8-b3d8-7a3f60de8808)

But yeah, I agree, using references should be memory efficient and I would prefer to implement it that way if it's reasonably straightforward. Although, I believe we shouldn't optimize for the sake of optimization (aka "premature optimization"). What do you think :slightly_smiling_face:

**Comment by neon-mmd** [comment]
> > Also, one thing I would like to suggest that is that you don't need to add `to_vec()` because the `.bytes()` function already returns a `vec<u8>` so converting a vec fo a vec does not make sense like it would be an unnecessary conversion and also redundant too.
> 
> Can you clarify this for me because I might be missing something here. Because the compiler advises me to use the `.to_vec()` method. I'm fairly new to the library and the language so please excuse me if I missed something 😅
> 
> ![2024-01-29_19-00](https://private-user-images.githubusercontent.com/31008330/300429764-f741cc9d-5c3f-4ba8-b3d8-7a3f60de8808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDE5OTAsIm5iZiI6MTcwNjU0MTY5MCwicGF0aCI6Ii8zMTAwODMzMC8zMDA0Mjk3NjQtZjc0MWNjOWQtNWMzZi00YmE4LWIzZDgtN2EzZjYwZGU4ODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MjEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNjQ1YzE1M2I5NmU5ZTdmNmU3NDUyMGE5MzdhYzIwYzBmZGQ3YTBjMDRjYzljZWFkZWU3ZTA3MTRiNzhmZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a-RsfIZliUSVUAjZi_YFPbZTFaPS2yNCf6y5iU3ZUXw)
> 
> But yeah, I agree, using references should be memory efficient and I would prefer to implement it that way if it's reasonably straightforward. Although, I believe we shouldn't optimize for the sake of optimization (aka "premature optimization"). What do you think 🙂

Yes, I agree, also I think from the compilor error it seems that you will have to go with the `to_vec()` method to fix this error. So I think that's the only way to fix this. So I would suggest going with the `to_vec()` method. :slightly_smiling_face:
