### ISSUE TITLE
Write an about page for the project in the website with appropriate css styling

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#5]
At present the about page of the website just contains dummy text and it needs to show a clear and concise description about the project in the website. The about page's html code (which uses handlebars templating) is located under the `public/templates/` folder in the project and its `css stylesheet` is located under `public/static/themes` folder. 

`Note:` All contributions should go into the rolling branch of this repository and before you contribute make sure you have `cc-cli` installed on your system otherwise you can install by following the installation instructions [here](https://crates.io/crates/cc-cli) `fork this project` add your appropriate changes to your fork and then `add a PR mentioning this issue`.

**Comment by bcsamrudh** [comment]
@neon-mmd . I wish to work on  to this Issue.

**Comment by neon-mmd** [comment]
Ok sure :slightly_smiling_face: , you can start by forking this project and adding the changes that are required and then you can submit a PR to the rolling branch.

Also, I have a discord channel on this project if you wish to join in, we can discuss anything related to the project over there :smile: .  Here is the invite [link](https://discord.gg/P5tctXVGs2). 

Also if you tend to be regular in the contributions, I will be looking forward to assigning you a role in this project soon :smile:.

**Comment by bcsamrudh** [comment]
Thanks 😊, I have already joined the discord server!

**Comment by bcsamrudh** [comment]
![image](https://github.com/neon-mmd/websurfx/assets/114090255/36ae2810-b455-4308-a3e5-b533e8604d25)

@neon-mmd Is this good or do you suggest any changes.

**Comment by bcsamrudh** [comment]
@neon-mmd , I will make changes.

**Comment by bcsamrudh** [comment]
@neon-mmd Should there be an Underline beneath the word Websurfx or as shown in the above Image.

**Comment by bcsamrudh** [comment]
![image](https://github.com/neon-mmd/websurfx/assets/114090255/f58041b4-f65d-433e-9800-7b5ea79f2aa7)
@neon-mmd , How about this!

**Comment by neon-mmd** [comment]
I think that look's great!! :+1:. I think you can open a PR if you wish or maybe we could have another look by another team member before opening the PR. what do you say??

**Comment by bcsamrudh** [comment]
I think it would be good if another team member review it.

**Comment by neon-mmd** [comment]
Ok, I feel the PR would be an appropriate place for everyone to review so I would suggest you open a PR with the changes, and let's see if everyone likes it :smile: .
