### ISSUE TITLE
:children_crossing: Thin `lto` for the compilation instead of fat `lto` to improve build times 

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#516]
#### Work Expected From This Issue
Change the `lto` option in the release section/profile of the `Cargo.toml` file from true to `thin`. 

This issue expects the following files to be changed:
- `Cargo.toml`

> [!Note]
> All files to be modified are located under the codebase (`websurfx` directory).

#### Reason Behind These Changes
The reasons behind having these changes is to reduce the build time when building the app which helps improve the user experience.

#### Sample Code
The changes that should be made in the `Cargo.toml` file, are as shown below:
```diff
[package]
name = "websurfx"
version = "1.9.4"
edition = "2021"
description = "An open-source alternative to Searx that provides clean, ad-free, and organic results with incredible speed while keeping privacy and security in mind."
repository = "https://github.com/neon-mmd/websurfx"
license = "AGPL-3.0"

[[bin]]
name = "websurfx"
test = true
bench = false
path = "src/bin/websurfx.rs"

[dependencies]
reqwest = {version="0.11.22", default-features=false, features=["rustls-tls","brotli", "gzip"]}
tokio = {version="1.32.0",features=["rt-multi-thread","macros"], default-features = false}
serde = {version="1.0.196", default-features=false, features=["derive"]}
serde_json = {version="1.0.109", default-features=false}
maud = {version="0.25.0", default-features=false, features=["actix-web"]}
scraper = {version="0.18.1", default-features = false}
actix-web = {version="4.4.0", features = ["cookies", "macros", "compress-brotli"], default-features=false}
actix-files = {version="0.6.5", default-features=false}
actix-cors = {version="0.6.4", default-features=false}
fake-useragent = {version="0.1.3", default-features=false}
env_logger = {version="0.11.1", default-features=false}
log = {version="0.4.20", default-features=false}
mlua = {version="0.9.1", features=["luajit", "vendored"], default-features=false}
redis = {version="0.24.0", features=["tokio-comp","connection-manager"], default-features = false, optional = true}
blake3 = {version="1.5.0", default-features=false}
error-stack = {version="0.4.0", default-features=false, features=["std"]}
async-trait = {version="0.1.76", default-features=false}
regex = {version="1.9.4", features=["perf"], default-features = false}
smallvec = {version="1.13.1", features=["union", "serde"], default-features=false}
futures = {version="0.3.28", default-features=false}
dhat = {version="0.3.2", optional = true, default-features=false}
mimalloc = { version = "0.1.38", default-features = false }
async-once-cell = {version="0.5.3", default-features=false}
actix-governor = {version="0.5.0", default-features=false}
mini-moka = { version="0.10", optional = true, default-features=false, features=["sync"]}
brotli = { version = "3.4.0", default-features = false, features=["std"], optional=true}
chacha20poly1305={version="0.10.1", default-features=false, features=["alloc","getrandom"], optional=true}
chacha20 = {version="0.9.1", default-features=false, optional=true}
base64 = {version="0.21.5", default-features=false, features=["std"], optional=true}
cfg-if = {version="1.0.0", default-features=false,optional=true}

[dev-dependencies]
rusty-hook = {version="^0.11.2", default-features=false}
criterion = {version="0.5.1", default-features=false}
tempfile = {version="3.8.0", default-features=false}

[build-dependencies]
lightningcss = {version="1.0.0-alpha.52", default-features=false, features=["grid"]}
minify-js = {version="0.6.0", default-features=false}

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = 'unpacked'
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false # This should only be commented when testing with dhat profiler
# debug = 1 # This should only be uncommented when testing with dhat profiler
split-debuginfo = '...'
debug-assertions = false
overflow-checks = false
-lto = true
+lto = 'thin'
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false
strip = "debuginfo"

[features]
default = ["memory-cache"]
dhat-heap = ["dep:dhat"] 
memory-cache = ["dep:mini-moka"]
redis-cache = ["dep:redis","dep:base64"]
compress-cache-results = ["dep:brotli","dep:cfg-if"]
encrypt-cache-results = ["dep:chacha20poly1305","dep:chacha20"]
cec-cache-results = ["compress-cache-results","encrypt-cache-results"]
```

> [!Note]
> 1. To get started contributing make sure to read the `contributing.md` file for the guidlines on how to contribute in this project
> 2. To contribute first fork this project by following this [video](https://www.youtube.com/watch?v=FnxFwyzm4Z4) tutorial if you are not familliar with process and add your changes and make a pull request with the changes to this repository and if you are new to GitHub then follow this [video](https://www.youtube.com/watch?v=8B_JWf7pG20) tutorial to get started contributing :slightly_smiling_face: .

### Do you want to work on this issue?

None

### Additional information
Here are some resources on thin LTO:
- https://piped.video/watch?v=p9nH2vZ2mNo
- https://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html

**Comment by Kranzes** [comment]
This is a release build, shouldn't we use LTO for max performance and smallest binary size?

**Comment by neon-mmd** [comment]
> This is a release build, shouldn't we use LTO for max performance and smallest binary size?

Yes, we are using LTO but with this issue we are just moving away from fat LTO to thin LTO because thin LTO uses a different algorithm to optimize code but the results are exactly the same as fat LTO but the only difference between the two is that fat LTO is slower not very scalable but thin LTO is both scalable and fast. So that's why this issue proposes on chaning the LTO option from fat to thin.

Also, for more information on different LTO option, we would suggest going through the following cargo docs:

https://doc.rust-lang.org/cargo/reference/profiles.html#lto

Also, for more information on the difference on thin LTO and fat LTO. We would also suggest going through this talk:

https://piped.video/watch?v=p9nH2vZ2mNo

> [!Note]
> The above talk is a little old so it may contain some not very up to date information.

**Comment by evanyang1** [comment]
Ok i can try to work on this.

**Comment by neon-mmd** [comment]
> Ok i can try to work on this.

Ok sure, we will assign the issue to you. You may start working on it right away :rocket: :slightly_smiling_face: .
