### ISSUE TITLE
✨ restructure the config to have different layers for better composability 

### ISSUE THREAD

**Issue by Kranzes** [neon-mmd/websurfx#518]
### Description

Right now all of the config options are in one level (lua globals) this makes it more confusing to know which category each setting is related to. In addition, we can use mlua's serde feature to de-serialize directly from that structure. 

### Do you want to work on this issue?

Yes

**Comment by neon-mmd** [comment]
As you have requested to work on this issue, we have assigned this issue to you. You may start working on it right away :rocket: :slightly_smiling_face: .
