### ISSUE TITLE
✨ Initial support for low powered devices with other architectures

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#566]
#### Work Expected From The Issue
Provide initial support for low powered devices with other architectures by providing different cargo profiles to support different architectures.

The issue expects the following files to be changed/modified:
- `Cargo.toml`

> [!Note]
> All the files that are expected to be changed are located under the codebase (`websurfx` directory).

#### Reason Behind These Changes
The reason behind having these changes is to lay the initial groundwork of foundational support for low powered devices with other architectures, and which can be in future leveraged to expand support of the app to other architectures with further improvements and features provided in the code geared towards this.

### Do you want to work on this issue?

Yes

**Comment by lazyzyf** [comment]
Please release a docker image which can support arm64 platform.

**Comment by neon-mmd** [comment]
> Please release a docker image which can support arm64 platform.

Sorry for the late reply.
Yes sure, thanks :heart: for taking the time to add your feature request suggestion here but right now we are providing the initial support so that we can provide the base foundation for further features like this to be provided in the future releases. :slightly_smiling_face: .

Also, we would suggest you also open a feature request issue for this. So that we can work on that in the future releases soon. :slightly_smiling_face:
