### ISSUE TITLE
Make about page centered

### ISSUE THREAD

**Issue by neon-mmd** [neon-mmd/websurfx#59]
Put some margins on the right and left of the content of the `About Page` to make it centered on the website to make it visually look better by using percentage values for the margins instead of using fixed values like `rem`, `em`, `px`, etc. 

![image](https://github.com/neon-mmd/websurfx/assets/132049916/2394a779-2328-4d43-926b-b6f2a5351240)

The target file that needs to be changed is located under `public/static/themes` and it is called `simple.css`.

**Comment by sathiyaIbe** [comment]
How we can find which class name we need to modify in it?

**Comment by neon-mmd** [comment]
My bad, I forgot to mention the class name to be modified. It is called `.about-container` and can be found in `public/static/themes/simple.css`. Thanks for asking the question and pointing out my mistake :slightly_smiling_face: .

Also, one more thing before you make the change. Make sure to read the `contributing.md` thoroughly then start adding PRs here :slightly_smiling_face: .

**Comment by sam-sunder** [comment]
Hi I'd like to do this. Can I get involved?

**Comment by neon-mmd** [comment]
> Hi I'd like to do this. Can I get involved?

Yes, sure go ahead :+1:  :slightly_smiling_face:, I would be glad to have a new PR from your side :slightly_smiling_face: .

**Comment by sam-sunder** [comment]
I Opened a new PR as per your guidelines. You may review it

**Comment by neon-mmd** [comment]
> I Opened a new PR as per your guidelines. You may review it

Yes sure :slightly_smiling_face: I will review it right away.

**Comment by bcsamrudh** [comment]
@neon-mmd But the about page was centered when I made it.

**Comment by neon-mmd** [comment]
> @neon-mmd But the about page was centered when I made it.

I don't know then maybe there was some problem with the code or maybe you forgot to add it like you wrote it maybe on your side but then forgot to add it, anyways @sam-sunder fixed the problem. I really appreciate his work :+1: as well as @bcsamrudh  for working on the `About page`. Thanks!! :heart:  to both of you guys.

**Comment by sam-sunder** [comment]
@bcsamrudh About page is centered only on large screens when you made it as the `align-items: center` is set but it won't work on small screens.
