### ISSUE TITLE
:bug: Results are often prefixed with `localhost:port` which result in 404

### ISSUE THREAD

**Issue by stef204** [neon-mmd/websurfx#631]
### Description

On branch `rolling`.

Very often, when searching, the results page will show a number of links to websites/webpages which include both valid links and invalid ones--resulting in error 404.

The invalid links are prefixed with `http://localhost:port/` which of course results in 404.

One can just hover the mouse over the various results and see which links are valid and which are not.

This is definitely something which needs to be resolved.  Unless I my config file is misconfigured, creating the problem.

### Do you want to work on this issue?

None

### Additional information

`config.lua` is [here](https://paste.xinu.at/NyKClQsE/)

**Comment by neon-mmd** [comment]
Sorry for the late reply.

Thanks ❤️ for taking the time to report this issue. We really appreciate it as this helps improves the project. 🙂 .

My best guess is this issue maybe due to breaking API changes from the upstream search engines which could be causing the wrong search results being grabbed from the above search engines rather than from the config file. @jfvillablanca What do you think? Also, if you are free, could you investigate more into this. 😅

**Comment by jfvillablanca** [comment]
Yeah, I think you might be right, it probably has something to do breaking changes upstream. I'll take a look at this

If you could provide a minimal way to reproduce this issue, I would be most grateful :smile: 

Edit:
I think the affected engine is Mojeek; currently investigating

**Comment by stef204** [comment]
I've been waiting 3 weeks to mention that this seems to only happen with the `mojeek` search engine ;)
So enable that in `config.lua` and search, look at results.
Thanks.

**Comment by neon-mmd** [comment]
@stef204 

Thanks ❤️ once again for reporting this issue. We really appreciate it. Now we have fixed/resolved this issue in the PR #640 . But if you still face any issues feel free to reopen this issue and provide us an update on this issue. 🙂

**Comment by stef204** [comment]
Thanks for the work.
Unfortunately, the issue is back (not fixed.)
I pulled the latest `rolling` and `cargo clean` and recompiled.
Fired up `websurfx` and looked good on the first two searches.
Trying again after that, brought back the results being prefixed as described above, resulting in `404`.
Not sure what is going on here.  Will try to test further but this is what is happening currently.
