### ISSUE TITLE
Provide a fix for `Contributor List` github action

### ISSUE THREAD

**Issue by xffxff** [neon-mmd/websurfx#95]
Provide a fix to the GitHub action to generate a contributors' list by fixing the problems which have appeared in the logs and in the image shown below.

![image](https://github.com/neon-mmd/websurfx/assets/30254428/f5357064-22fc-4e86-98f2-0eb356e8ff13)

**Logs**:  https://github.com/neon-mmd/websurfx/actions/runs/5161278677/jobs/9298133910

**Comment by neon-mmd** [comment]
Since the contributors' list seem to be working fine without the need of GitHub action. I think we will not need this action anymore. That's why I am closing this issue :slightly_smiling_face: .

Thanks :heart: for working on this action and highlighting this issue :slightly_smiling_face: .
